/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.19
 * Generated at: 2026-03-02 03:39:51 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.List;

public final class admin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/admin_sidebar.jsp", Long.valueOf(1772422274000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(1);
    _jspx_imports_classes.add("java.util.List");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("        <!DOCTYPE html>\r\n");
      out.write("        <html lang=\"vi\">\r\n");
      out.write("\r\n");
      out.write("        <head>\r\n");
      out.write("            <meta charset=\"UTF-8\">\r\n");
      out.write("            <title>Admin Dashboard | Shopee Clone</title>\r\n");
      out.write("            <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("            <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css\">\r\n");
      out.write("            <script src=\"https://cdn.jsdelivr.net/npm/chart.js\"></script>\r\n");
      out.write("            <link href=\"https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap\"\r\n");
      out.write("                rel=\"stylesheet\">\r\n");
      out.write("            <style>\r\n");
      out.write("                :root {\r\n");
      out.write("                    --shopee-primary: #ee4d2d;\r\n");
      out.write("                    --shopee-hover: #f05d40;\r\n");
      out.write("                    --sidebar-width: 260px;\r\n");
      out.write("                    --bg-color: #f5f5f5;\r\n");
      out.write("                    --card-shadow: 0 1px 3px rgba(0, 0, 0, 0.12), 0 1px 2px rgba(0, 0, 0, 0.24);\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                body {\r\n");
      out.write("                    background: var(--bg-color);\r\n");
      out.write("                    font-family: 'Inter', sans-serif;\r\n");
      out.write("                    overflow-x: hidden;\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                .sidebar {\r\n");
      out.write("                    height: 100vh;\r\n");
      out.write("                    background: #ffffff;\r\n");
      out.write("                    width: var(--sidebar-width);\r\n");
      out.write("                    position: fixed;\r\n");
      out.write("                    box-shadow: 2px 0 10px rgba(0, 0, 0, 0.05);\r\n");
      out.write("                    z-index: 100;\r\n");
      out.write("                    overflow-y: auto;\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                .sidebar-logo {\r\n");
      out.write("                    display: flex;\r\n");
      out.write("                    align-items: center;\r\n");
      out.write("                    justify-content: center;\r\n");
      out.write("                    padding: 20px 0;\r\n");
      out.write("                    border-bottom: 1px solid #eee;\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                .sidebar-logo h4 {\r\n");
      out.write("                    color: var(--shopee-primary);\r\n");
      out.write("                    font-weight: 700;\r\n");
      out.write("                    margin: 0;\r\n");
      out.write("                    font-size: 22px;\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                .nav-item {\r\n");
      out.write("                    padding: 5px 15px;\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                .sidebar a {\r\n");
      out.write("                    color: #555;\r\n");
      out.write("                    text-decoration: none;\r\n");
      out.write("                    padding: 12px 20px;\r\n");
      out.write("                    display: flex;\r\n");
      out.write("                    align-items: center;\r\n");
      out.write("                    border-radius: 8px;\r\n");
      out.write("                    font-weight: 500;\r\n");
      out.write("                    transition: all 0.2s ease;\r\n");
      out.write("                    margin-bottom: 5px;\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                .sidebar a i {\r\n");
      out.write("                    width: 30px;\r\n");
      out.write("                    font-size: 18px;\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                .sidebar a:hover {\r\n");
      out.write("                    background-color: #fef0ee;\r\n");
      out.write("                    color: var(--shopee-primary);\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                .sidebar a.active {\r\n");
      out.write("                    background-color: var(--shopee-primary);\r\n");
      out.write("                    color: #ffffff;\r\n");
      out.write("                    box-shadow: 0 4px 6px rgba(238, 77, 45, 0.2);\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                .main-content {\r\n");
      out.write("                    margin-left: var(--sidebar-width);\r\n");
      out.write("                    padding: 30px 40px;\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                /* Header */\r\n");
      out.write("                .top-header {\r\n");
      out.write("                    display: flex;\r\n");
      out.write("                    justify-content: space-between;\r\n");
      out.write("                    align-items: center;\r\n");
      out.write("                    background: #fff;\r\n");
      out.write("                    padding: 15px 30px;\r\n");
      out.write("                    border-radius: 12px;\r\n");
      out.write("                    box-shadow: var(--card-shadow);\r\n");
      out.write("                    margin-bottom: 30px;\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                /* Stats Cards */\r\n");
      out.write("                .stat-card {\r\n");
      out.write("                    border: none;\r\n");
      out.write("                    border-radius: 12px;\r\n");
      out.write("                    background: #fff;\r\n");
      out.write("                    box-shadow: var(--card-shadow);\r\n");
      out.write("                    transition: transform 0.3s ease;\r\n");
      out.write("                    overflow: hidden;\r\n");
      out.write("                    position: relative;\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                .stat-card:hover {\r\n");
      out.write("                    transform: translateY(-5px);\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                .stat-icon {\r\n");
      out.write("                    position: absolute;\r\n");
      out.write("                    right: -20px;\r\n");
      out.write("                    bottom: -20px;\r\n");
      out.write("                    font-size: 100px;\r\n");
      out.write("                    opacity: 0.1;\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                .card-revenue {\r\n");
      out.write("                    background: linear-gradient(135deg, #ee4d2d, #ff7b54);\r\n");
      out.write("                    color: white;\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                .card-orders {\r\n");
      out.write("                    background: linear-gradient(135deg, #28a745, #4cd137);\r\n");
      out.write("                    color: white;\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                .card-users {\r\n");
      out.write("                    background: linear-gradient(135deg, #007bff, #00a8ff);\r\n");
      out.write("                    color: white;\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                .card-products {\r\n");
      out.write("                    background: linear-gradient(135deg, #6f42c1, #a855f7);\r\n");
      out.write("                    color: white;\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                /* Chart Box */\r\n");
      out.write("                .chart-box {\r\n");
      out.write("                    background: #fff;\r\n");
      out.write("                    padding: 25px;\r\n");
      out.write("                    border-radius: 12px;\r\n");
      out.write("                    box-shadow: var(--card-shadow);\r\n");
      out.write("                    height: 100%;\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                .chart-title {\r\n");
      out.write("                    font-weight: 600;\r\n");
      out.write("                    color: #333;\r\n");
      out.write("                    margin-bottom: 20px;\r\n");
      out.write("                    font-size: 17px;\r\n");
      out.write("                    border-left: 4px solid var(--shopee-primary);\r\n");
      out.write("                    padding-left: 10px;\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                /* Recent orders table */\r\n");
      out.write("                .badge-pending {\r\n");
      out.write("                    background: #fff3cd;\r\n");
      out.write("                    color: #856404;\r\n");
      out.write("                    font-weight: 600;\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                .badge-completed {\r\n");
      out.write("                    background: #d4edda;\r\n");
      out.write("                    color: #155724;\r\n");
      out.write("                    font-weight: 600;\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                .badge-cancelled {\r\n");
      out.write("                    background: #f8d7da;\r\n");
      out.write("                    color: #721c24;\r\n");
      out.write("                    font-weight: 600;\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                .badge-paid {\r\n");
      out.write("                    background: #cce5ff;\r\n");
      out.write("                    color: #004085;\r\n");
      out.write("                    font-weight: 600;\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                .badge-shipped {\r\n");
      out.write("                    background: #e2e3f1;\r\n");
      out.write("                    color: #383d6e;\r\n");
      out.write("                    font-weight: 600;\r\n");
      out.write("                }\r\n");
      out.write("            </style>\r\n");
      out.write("        </head>\r\n");
      out.write("\r\n");
      out.write("        <body>\r\n");
      out.write("\r\n");
      out.write("            <!-- Sidebar -->\r\n");
      out.write("            ");
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
 String currentPage = request.getServletPath(); 
      out.write("\r\n");
      out.write("<div class=\"sidebar d-flex flex-column\" style=\"overflow-y: auto;\">\r\n");
      out.write("    <div class=\"sidebar-logo\">\r\n");
      out.write("        <h4><i class=\"fas fa-shopping-bag me-1\"></i> Admin Panel</h4>\r\n");
      out.write("    </div>\r\n");
      out.write("    ");
 model.User s_admin = (model.User) session.getAttribute("account"); 
      out.write("\r\n");
      out.write("    <div class=\"mt-4 flex-grow-1\" style=\"overflow-y: auto; padding-bottom: 10px;\">\r\n");
      out.write("        ");
 if (s_admin != null && s_admin.hasPermission("VIEW_DASHBOARD")) { 
      out.write("\r\n");
      out.write("        <div class=\"nav-item\"><a href=\"admin\" class=\"");
      out.print( "/admin".equals(currentPage) ? "active" : "" );
      out.write("\"><i class=\"fas fa-chart-pie\"></i> T&#7893;ng Quan</a></div>\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("        ");
 if (s_admin != null && s_admin.hasPermission("MANAGE_ROLES")) { 
      out.write("\r\n");
      out.write("        <div class=\"nav-item\"><a href=\"admin-roles\" class=\"");
      out.print( "/admin-roles".equals(currentPage) ? "active" : "" );
      out.write("\"><i class=\"fas fa-user-shield\"></i> Nh&#243;m Quy&#7873;n</a></div>\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("        ");
 if (s_admin != null && s_admin.hasPermission("MANAGE_SYSTEM")) { 
      out.write("\r\n");
      out.write("        <div class=\"nav-item\"><a href=\"admin-import\" class=\"");
      out.print( "/admin-import".equals(currentPage) ? "active" : "" );
      out.write("\"><i class=\"fas fa-database\"></i> Qu&#7843;n l&#253; D&#7919; Li&#7879;u</a></div>\r\n");
      out.write("        <div class=\"nav-item\"><a href=\"admin-settings\" class=\"");
      out.print( "/admin-settings".equals(currentPage) ? "active" : "" );
      out.write("\"><i class=\"fas fa-cog\"></i> C&#7845;u H&#236;nh H&#7879; Th&#7889;ng</a></div>\r\n");
      out.write("        <div class=\"nav-item\"><a href=\"admin-generate\" class=\"");
      out.print( "/admin-generate".equals(currentPage) ? "active" : "" );
      out.write("\"><i class=\"fas fa-magic\"></i> T&#7841;o D&#7919; Li&#7879;u</a></div>\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("        ");
 if (s_admin != null && s_admin.hasPermission("MANAGE_PRODUCTS")) { 
      out.write("\r\n");
      out.write("        <div class=\"nav-item\"><a href=\"admin-products\" class=\"");
      out.print( "/admin-products".equals(currentPage) ? "active" : "" );
      out.write("\"><i class=\"fas fa-box-open\"></i> S&#7843;n Ph&#7849;m</a></div>\r\n");
      out.write("        <div class=\"nav-item\"><a href=\"admin-categories\" class=\"");
      out.print( "/admin-categories".equals(currentPage) ? "active" : "" );
      out.write("\"><i class=\"fas fa-tags\"></i> Danh M&#7909;c</a></div>\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("        ");
 if (s_admin != null && s_admin.hasPermission("MANAGE_ORDERS")) { 
      out.write("\r\n");
      out.write("        <div class=\"nav-item\"><a href=\"admin-orders\" class=\"");
      out.print( "/admin-orders".equals(currentPage) ? "active" : "" );
      out.write("\"><i class=\"fas fa-clipboard-list\"></i> &#272;&#417;n H&#224;ng</a></div>\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("        ");
 if (s_admin != null && s_admin.hasPermission("MANAGE_USERS")) { 
      out.write("\r\n");
      out.write("        <div class=\"nav-item\"><a href=\"admin-users\" class=\"");
      out.print( "/admin-users".equals(currentPage) ? "active" : "" );
      out.write("\"><i class=\"fas fa-users\"></i> Kh&#225;ch H&#224;ng</a></div>\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("        <div class=\"nav-item\"><a href=\"admin-reviews\" class=\"");
      out.print( "/admin-reviews".equals(currentPage) ? "active" : "" );
      out.write("\"><i class=\"fas fa-star-half-alt\"></i> X&#233;t Duy&#7879;t &#272;&#225;nh Gi&#225;</a></div>\r\n");
      out.write("        <div class=\"nav-item\"><a href=\"admin-alerts\" class=\"");
      out.print( "/admin-alerts".equals(currentPage) ? "active" : "" );
      out.write("\"><i class=\"fas fa-exclamation-triangle\"></i> C&#7843;nh B&#225;o B&#7845;t Th&#432;&#7901;ng</a></div>\r\n");
      out.write("        ");
 if (s_admin != null && s_admin.hasPermission("VIEW_AUDIT_LOGS")) { 
      out.write("\r\n");
      out.write("        <div class=\"nav-item\"><a href=\"admin-logs\" class=\"");
      out.print( "/admin-logs".equals(currentPage) ? "active" : "" );
      out.write("\"><i class=\"fas fa-history\"></i> Nh&#7853;t K&#253;</a></div>\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("        <div class=\"nav-item\"><a href=\"home\" target=\"_blank\"><i class=\"fas fa-globe\"></i> Truy C&#7853;p C&#7917;a H&#224;ng</a></div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"nav-item mb-4 border-top pt-3\">\r\n");
      out.write("        <a href=\"logout\" class=\"text-danger\"><i class=\"fas fa-sign-out-alt\"></i> &#272;&#259;ng Xu&#7845;t</a>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            <!-- Main Content -->\r\n");
      out.write("            <div class=\"main-content\">\r\n");
      out.write("                <!-- Header -->\r\n");
      out.write("                <div class=\"top-header\">\r\n");
      out.write("                    <div>\r\n");
      out.write("                        <h4 class=\"m-0 fw-bold text-dark\">Dashboard Thống Kê</h4>\r\n");
      out.write("                        <small class=\"text-muted\">Cập nhật số liệu theo thời gian thực</small>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"d-flex align-items-center gap-3\">\r\n");
      out.write("                        <!-- Global Search Button -->\r\n");
      out.write("                        <button class=\"btn btn-light rounded-circle shadow-sm\" type=\"button\" onclick=\"openGlobalSearch()\" title=\"Tìm kiếm toàn cục (Ctrl+K)\">\r\n");
      out.write("                            <i class=\"fas fa-search\"></i>\r\n");
      out.write("                        </button>\r\n");
      out.write("                        <div class=\"dropdown\">\r\n");
      out.write("                            <button class=\"btn btn-light rounded-circle shadow-sm position-relative\" type=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\r\n");
      out.write("                                <i class=\"fas fa-bell\"></i>\r\n");
      out.write("                                <span class=\"position-absolute top-0 start-100 translate-middle p-1 bg-danger rounded-circle\"></span>\r\n");
      out.write("                            </button>\r\n");
      out.write("                            <ul class=\"dropdown-menu dropdown-menu-end shadow border-0 mt-2\" style=\"width: 300px;\">\r\n");
      out.write("                                <li><h6 class=\"dropdown-header fw-bold text-dark\">Thông Báo</h6></li>\r\n");
      out.write("                                <li><hr class=\"dropdown-divider\"></li>\r\n");
      out.write("                                <li><a class=\"dropdown-item text-center text-muted py-3\" href=\"#\">Chưa có thông báo mới nào</a></li>\r\n");
      out.write("                                <li><hr class=\"dropdown-divider\"></li>\r\n");
      out.write("                                <li><a class=\"dropdown-item text-center fw-medium text-primary\" href=\"#\">Xem tất cả</a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"d-flex align-items-center gap-2 border-start ps-3\">\r\n");
      out.write("                            <img src=\"https://ui-avatars.com/api/?name=Admin&background=ee4d2d&color=fff&rounded=true\"\r\n");
      out.write("                                width=\"45\">\r\n");
      out.write("                            <div class=\"d-flex flex-column\">\r\n");
      out.write("                                <span class=\"fw-bold\" style=\"font-size: 14px;\">Super Admin</span>\r\n");
      out.write("                                <span class=\"text-muted\" style=\"font-size: 12px;\">Quản trị viên</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <!-- Dashboard Stats: 4 cards -->\r\n");
      out.write("                <div class=\"row g-4 mb-4\">\r\n");
      out.write("                    <div class=\"col-xl-3 col-md-6\">\r\n");
      out.write("                        <div class=\"stat-card card-revenue p-4\">\r\n");
      out.write("                            <div class=\"d-flex flex-column\">\r\n");
      out.write("                                <span class=\"text-uppercase fw-bold mb-1 opacity-75\"\r\n");
      out.write("                                    style=\"letter-spacing: 1px; font-size: 13px;\">Tổng Doanh Thu</span>\r\n");
      out.write("                                <h2 class=\"fw-bold m-0 mt-2\">₫");
      out.print( String.format("%,.0f",
                                        request.getAttribute("totalRevenue")));
      out.write("\r\n");
      out.write("                                </h2>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <i class=\"fas fa-wallet stat-icon\"></i>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-xl-3 col-md-6\">\r\n");
      out.write("                        <div class=\"stat-card card-orders p-4\">\r\n");
      out.write("                            <div class=\"d-flex flex-column\">\r\n");
      out.write("                                <span class=\"text-uppercase fw-bold mb-1 opacity-75\"\r\n");
      out.write("                                    style=\"letter-spacing: 1px; font-size: 13px;\">Tổng Đơn Hàng</span>\r\n");
      out.write("                                <h2 class=\"fw-bold m-0 mt-2\">\r\n");
      out.write("                                    ");
      out.print( request.getAttribute("totalOrders"));
      out.write(" <small\r\n");
      out.write("                                            class=\"fs-6 fw-normal opacity-75\">đơn</small>\r\n");
      out.write("                                </h2>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <i class=\"fas fa-shopping-bag stat-icon\"></i>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-xl-3 col-md-6\">\r\n");
      out.write("                        <div class=\"stat-card card-users p-4\">\r\n");
      out.write("                            <div class=\"d-flex flex-column\">\r\n");
      out.write("                                <span class=\"text-uppercase fw-bold mb-1 opacity-75\"\r\n");
      out.write("                                    style=\"letter-spacing: 1px; font-size: 13px;\">Người Dùng</span>\r\n");
      out.write("                                <h2 class=\"fw-bold m-0 mt-2\">\r\n");
      out.write("                                    ");
      out.print( request.getAttribute("totalUsers"));
      out.write(" <small\r\n");
      out.write("                                            class=\"fs-6 fw-normal opacity-75\">user</small>\r\n");
      out.write("                                </h2>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <i class=\"fas fa-users stat-icon\"></i>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-xl-3 col-md-6\">\r\n");
      out.write("                        <div class=\"stat-card card-products p-4\">\r\n");
      out.write("                            <div class=\"d-flex flex-column\">\r\n");
      out.write("                                <span class=\"text-uppercase fw-bold mb-1 opacity-75\"\r\n");
      out.write("                                    style=\"letter-spacing: 1px; font-size: 13px;\">Sản Phẩm</span>\r\n");
      out.write("                                <h2 class=\"fw-bold m-0 mt-2\">\r\n");
      out.write("                                    ");
      out.print( request.getAttribute("totalProducts"));
      out.write(" <small\r\n");
      out.write("                                            class=\"fs-6 fw-normal opacity-75\">SP</small>\r\n");
      out.write("                                </h2>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <i class=\"fas fa-box-open stat-icon\"></i>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <!-- Charts -->\r\n");
      out.write("                <div class=\"row g-4 mb-4\">\r\n");
      out.write("                    <div class=\"col-xl-8 col-lg-7\">\r\n");
      out.write("                        <div class=\"chart-box\">\r\n");
      out.write("                            <h5 class=\"chart-title\">Doanh Thu 7 Ngày Gần Nhất</h5>\r\n");
      out.write("                            <canvas id=\"revenueChart\" height=\"120\"></canvas>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-xl-4 col-lg-5\">\r\n");
      out.write("                        <div class=\"chart-box\">\r\n");
      out.write("                            <h5 class=\"chart-title\">Tỷ Lệ Đơn Hàng</h5>\r\n");
      out.write("                            <div class=\"d-flex justify-content-center align-items-center\" style=\"height: 250px;\">\r\n");
      out.write("                                <canvas id=\"statusChart\"></canvas>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <!-- Recent Orders & Top Products -->\r\n");
      out.write("                <div class=\"row g-4 mb-4\">\r\n");
      out.write("                    <div class=\"col-xl-8 col-lg-7\">\r\n");
      out.write("                        <div class=\"chart-box\">\r\n");
      out.write("                            <div class=\"d-flex justify-content-between align-items-center mb-3\">\r\n");
      out.write("                                <h5 class=\"chart-title m-0\">Đơn Hàng Gần Đây</h5>\r\n");
      out.write("                                <a href=\"admin-orders\" class=\"btn btn-sm btn-outline-danger\">Xem tất cả <i\r\n");
      out.write("                                        class=\"fas fa-arrow-right ms-1\"></i></a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"table-responsive\">\r\n");
      out.write("                                <table class=\"table table-hover border align-middle mb-0\">\r\n");
      out.write("                                    <thead class=\"table-light\">\r\n");
      out.write("                                        <tr>\r\n");
      out.write("                                            <th width=\"80\">Mã ĐH</th>\r\n");
      out.write("                                            <th>Khách Hàng</th>\r\n");
      out.write("                                            <th width=\"150\" class=\"text-end\">Tổng Tiền</th>\r\n");
      out.write("                                            <th width=\"140\" class=\"text-center\">Trạng Thái</th>\r\n");
      out.write("                                            <th width=\"180\">Ngày Tạo</th>\r\n");
      out.write("                                        </tr>\r\n");
      out.write("                                    </thead>\r\n");
      out.write("                                    <tbody>\r\n");
      out.write("                                        ");
 List<String[]> recentOrders = (List<String[]>)
                                                request.getAttribute("recentOrders");
                                                if(recentOrders != null && !recentOrders.isEmpty()) {
                                                for(String[] o : recentOrders) {
                                                String statusClass = "badge-pending";
                                                if("COMPLETED".equals(o[3])) statusClass = "badge-completed";
                                                else if("CANCELLED".equals(o[3])) statusClass = "badge-cancelled";
                                                else if("PAID".equals(o[3])) statusClass = "badge-paid";
                                                else if("SHIPPED".equals(o[3])) statusClass = "badge-shipped";
                                                
      out.write("\r\n");
      out.write("                                                <tr>\r\n");
      out.write("                                                    <td class=\"fw-bold\">#");
      out.print( o[0] );
      out.write("\r\n");
      out.write("                                                    </td>\r\n");
      out.write("                                                    <td><i class=\"fas fa-user-circle text-muted me-1\"></i>\r\n");
      out.write("                                                        ");
      out.print( o[1] );
      out.write("\r\n");
      out.write("                                                    </td>\r\n");
      out.write("                                                    <td class=\"text-end text-danger fw-bold\">\r\n");
      out.write("                                                        ");
      out.print( String.format("%,.0f", Double.parseDouble(o[2])) );
      out.write(" đ\r\n");
      out.write("                                                    </td>\r\n");
      out.write("                                                    <td class=\"text-center\">\r\n");
      out.write("                                                        <span class=\"badge rounded-pill px-3 py-2 ");
      out.print( statusClass );
      out.write("\">\r\n");
      out.write("                                                            ");
      out.print( o[3] );
      out.write("\r\n");
      out.write("                                                        </span>\r\n");
      out.write("                                                    </td>\r\n");
      out.write("                                                    <td class=\"text-muted\" style=\"font-size: 13px;\"><i\r\n");
      out.write("                                                            class=\"fas fa-clock me-1\"></i>\r\n");
      out.write("                                                        ");
      out.print( o[4] );
      out.write("\r\n");
      out.write("                                                    </td>\r\n");
      out.write("                                                </tr>\r\n");
      out.write("                                                ");
 } } else { 
      out.write("\r\n");
      out.write("                                                <tr><td colspan=\"5\" class=\"text-center text-muted py-4\"><i class=\"fas fa-inbox fa-2x mb-2 d-block\"></i> Chưa có đơn hàng nào.</td></tr>\r\n");
      out.write("                                                ");
 } 
      out.write("\r\n");
      out.write("                                    </tbody>\r\n");
      out.write("                                </table>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                    <div class=\"col-xl-4 col-lg-5\">\r\n");
      out.write("                        <div class=\"chart-box\">\r\n");
      out.write("                            <h5 class=\"chart-title\">Top Sản Phẩm Bán Chạy</h5>\r\n");
      out.write("                            <div class=\"table-responsive\">\r\n");
      out.write("                                <table class=\"table table-hover border align-middle mb-0\">\r\n");
      out.write("                                    <thead class=\"table-light\">\r\n");
      out.write("                                        <tr>\r\n");
      out.write("                                            <th>Tên Sản Phẩm</th>\r\n");
      out.write("                                            <th width=\"80\" class=\"text-end\">Đã Bán</th>\r\n");
      out.write("                                        </tr>\r\n");
      out.write("                                    </thead>\r\n");
      out.write("                                    <tbody>\r\n");
      out.write("                                        ");
 List<String[]> topProducts = (List<String[]>) request.getAttribute("topProducts");
                                           if (topProducts != null && !topProducts.isEmpty()) {
                                               for (String[] tp : topProducts) { 
      out.write("\r\n");
      out.write("                                        <tr>\r\n");
      out.write("                                            <td class=\"text-truncate\" style=\"max-width: 150px;\" title=\"");
      out.print( tp[0] );
      out.write('"');
      out.write('>');
      out.print( tp[0] );
      out.write("</td>\r\n");
      out.write("                                            <td class=\"text-end fw-bold text-success\">");
      out.print( tp[1] );
      out.write("</td>\r\n");
      out.write("                                        </tr>\r\n");
      out.write("                                        ");
 } } else { 
      out.write("\r\n");
      out.write("                                        <tr><td colspan=\"2\" class=\"text-center text-muted\">Chưa có dữ liệu</td></tr>\r\n");
      out.write("                                        ");
 } 
      out.write("\r\n");
      out.write("                                    </tbody>\r\n");
      out.write("                                </table>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <!-- Recent Logs -->\r\n");
      out.write("                <div class=\"row g-4 mb-4\">\r\n");
      out.write("                    <div class=\"col-12\">\r\n");
      out.write("                        <div class=\"chart-box\">\r\n");
      out.write("                            <div class=\"d-flex justify-content-between align-items-center mb-3\">\r\n");
      out.write("                                <h5 class=\"chart-title m-0\">Nhật Ký Hoạt Động (Gần Đây)</h5>\r\n");
      out.write("                                <a href=\"admin-logs\" class=\"btn btn-sm btn-outline-primary\">Xem tất cả <i class=\"fas fa-arrow-right ms-1\"></i></a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"table-responsive\">\r\n");
      out.write("                                <table class=\"table table-hover border align-middle mb-0\">\r\n");
      out.write("                                    <thead class=\"table-light\">\r\n");
      out.write("                                        <tr>\r\n");
      out.write("                                            <th>Người Thực Hiện</th>\r\n");
      out.write("                                            <th>Hành Động</th>\r\n");
      out.write("                                            <th>Mục Tiêu</th>\r\n");
      out.write("                                            <th>Chi Tiết</th>\r\n");
      out.write("                                            <th width=\"180\">Thời Gian</th>\r\n");
      out.write("                                        </tr>\r\n");
      out.write("                                    </thead>\r\n");
      out.write("                                    <tbody>\r\n");
      out.write("                                        ");
 java.util.List<model.AuditLog> recentLogs = (java.util.List<model.AuditLog>) request.getAttribute("recentLogs");
                                           if (recentLogs != null && !recentLogs.isEmpty()) {
                                               for (model.AuditLog log : recentLogs) {
                                                   String actionClass = "bg-secondary";
                                                   if ("CREATE".equals(log.getAction())) actionClass = "bg-success";
                                                   else if ("UPDATE".equals(log.getAction())) actionClass = "bg-warning text-dark";
                                                   else if ("DELETE".equals(log.getAction())) actionClass = "bg-danger";
                                                   else if ("RESTORE".equals(log.getAction())) actionClass = "bg-info text-dark";
                                        
      out.write("\r\n");
      out.write("                                        <tr>\r\n");
      out.write("                                            <td class=\"fw-medium\"><i class=\"fas fa-user-shield text-muted me-1\"></i> ");
      out.print( log.getAdminName() != null ? log.getAdminName() : "Admin" );
      out.write("</td>\r\n");
      out.write("                                            <td><span class=\"badge ");
      out.print( actionClass );
      out.write('"');
      out.write('>');
      out.print( log.getAction() );
      out.write("</span></td>\r\n");
      out.write("                                            <td><span class=\"badge bg-light text-dark border\">");
      out.print( log.getTargetTable() );
      out.write("</span> (ID: ");
      out.print( log.getTargetId() );
      out.write(")</td>\r\n");
      out.write("                                            <td class=\"text-muted\">");
      out.print( log.getDetails() );
      out.write("</td>\r\n");
      out.write("                                            <td class=\"text-muted\" style=\"font-size: 13px;\"><i class=\"fas fa-clock me-1\"></i> ");
      out.print( new java.text.SimpleDateFormat("dd/MM/yyyy HH:mm").format(log.getCreatedAt()) );
      out.write("</td>\r\n");
      out.write("                                        </tr>\r\n");
      out.write("                                        ");
 } } else { 
      out.write("\r\n");
      out.write("                                        <tr><td colspan=\"5\" class=\"text-center text-muted\">Chưa có hoạt động nào</td></tr>\r\n");
      out.write("                                        ");
 } 
      out.write("\r\n");
      out.write("                                    </tbody>\r\n");
      out.write("                                </table>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <!-- Footer -->\r\n");
      out.write("                <div class=\"row g-4\">\r\n");
      out.write("                    <div class=\"col-12\">\r\n");
      out.write("                        <div class=\"chart-box p-3 text-center text-muted\">\r\n");
      out.write("                            &copy; 2026 Shopee Clone Admin System. Designed for Enterprise Management.\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <script>\r\n");
      out.write("                // Biểu đồ Doanh Thu Dạng Area (Đổ bóng mượt mà)\r\n");
      out.write("                const ctxRev = document.getElementById('revenueChart').getContext('2d');\r\n");
      out.write("\r\n");
      out.write("                let gradient = ctxRev.createLinearGradient(0, 0, 0, 400);\r\n");
      out.write("                gradient.addColorStop(0, 'rgba(238, 77, 45, 0.4)');\r\n");
      out.write("                gradient.addColorStop(1, 'rgba(238, 77, 45, 0.0)');\r\n");
      out.write("\r\n");
      out.write("                new Chart(ctxRev, {\r\n");
      out.write("                    type: 'line',\r\n");
      out.write("                    data: {\r\n");
      out.write("                        labels: ");
      out.print( request.getAttribute("chartLabels") );
      out.write(", // Dữ liệu Server\r\n");
      out.write("                        datasets: [{\r\n");
      out.write("                            label: 'Doanh thu (VNĐ)',\r\n");
      out.write("                            data: ");
      out.print( request.getAttribute("chartData") );
      out.write(", // Dữ liệu Server\r\n");
      out.write("                            fill: true,\r\n");
      out.write("                            backgroundColor: gradient,\r\n");
      out.write("                            borderColor: '#ee4d2d',\r\n");
      out.write("                            tension: 0.4, // Tạo đường cong mượt\r\n");
      out.write("                            borderWidth: 3,\r\n");
      out.write("                            pointBackgroundColor: '#fff',\r\n");
      out.write("                            pointBorderColor: '#ee4d2d',\r\n");
      out.write("                            pointBorderWidth: 2,\r\n");
      out.write("                            pointRadius: 4,\r\n");
      out.write("                            pointHoverRadius: 6\r\n");
      out.write("                        }]\r\n");
      out.write("                    },\r\n");
      out.write("                    options: {\r\n");
      out.write("                        responsive: true,\r\n");
      out.write("                        plugins: {\r\n");
      out.write("                            legend: { display: false } // Ẩn legend không cần thiết\r\n");
      out.write("                        },\r\n");
      out.write("                        scales: {\r\n");
      out.write("                            y: {\r\n");
      out.write("                                beginAtZero: true,\r\n");
      out.write("                                grid: { borderDash: [5, 5] }\r\n");
      out.write("                            },\r\n");
      out.write("                            x: {\r\n");
      out.write("                                grid: { display: false }\r\n");
      out.write("                            }\r\n");
      out.write("                        }\r\n");
      out.write("                    }\r\n");
      out.write("                });\r\n");
      out.write("\r\n");
      out.write("                // Biểu đồ Doughnut cho Trạng thái đơn (Dữ liệu thực)\r\n");
      out.write("                const ctxStatus = document.getElementById('statusChart').getContext('2d');\r\n");
      out.write("                new Chart(ctxStatus, {\r\n");
      out.write("                    type: 'doughnut',\r\n");
      out.write("                    data: {\r\n");
      out.write("                        labels: ['Hoàn thành', 'Chờ xử lý', 'Đã hủy'],\r\n");
      out.write("                        datasets: [{\r\n");
      out.write("                            data: [");
      out.print( request.getAttribute("ordersCompleted") );
      out.write(',');
      out.write(' ');
      out.print( request.getAttribute("ordersPending") );
      out.write(',');
      out.write(' ');
      out.print( request.getAttribute("ordersCancelled") );
      out.write("],\r\n");
      out.write("                            backgroundColor: ['#28a745', '#ffc107', '#dc3545'],\r\n");
      out.write("                            borderWidth: 0,\r\n");
      out.write("                            hoverOffset: 4\r\n");
      out.write("                        }]\r\n");
      out.write("                    },\r\n");
      out.write("                    options: {\r\n");
      out.write("                        responsive: true,\r\n");
      out.write("                        maintainAspectRatio: false,\r\n");
      out.write("                        plugins: {\r\n");
      out.write("                            legend: { position: 'bottom' }\r\n");
      out.write("                        },\r\n");
      out.write("                        cutout: '70%'\r\n");
      out.write("                    }\r\n");
      out.write("                });\r\n");
      out.write("            </script>\r\n");
      out.write("\r\n");
      out.write("            <!-- ============== GLOBAL SEARCH MODAL ============== -->\r\n");
      out.write("            <div id=\"globalSearchOverlay\" style=\"display:none; position:fixed; top:0; left:0; width:100vw; height:100vh; background:rgba(0,0,0,0.5); z-index:9999; backdrop-filter:blur(4px);\" onclick=\"closeGlobalSearch()\">\r\n");
      out.write("                <div style=\"max-width:680px; margin:80px auto; background:#fff; border-radius:16px; box-shadow:0 20px 60px rgba(0,0,0,0.3); overflow:hidden;\" onclick=\"event.stopPropagation()\">\r\n");
      out.write("                    <!-- Search Input -->\r\n");
      out.write("                    <div style=\"padding:20px 24px; border-bottom:1px solid #eee; display:flex; align-items:center; gap:12px;\">\r\n");
      out.write("                        <i class=\"fas fa-search\" style=\"color:#aaa; font-size:18px;\"></i>\r\n");
      out.write("                        <input id=\"globalSearchInput\" type=\"text\" placeholder=\"Tìm kiếm sản phẩm, người dùng, đơn hàng, danh mục...\"\r\n");
      out.write("                            style=\"border:none; outline:none; width:100%; font-size:16px; background:transparent;\"\r\n");
      out.write("                            oninput=\"debounceSearch(this.value)\" autocomplete=\"off\">\r\n");
      out.write("                        <kbd style=\"background:#f1f1f1; padding:2px 8px; border-radius:4px; font-size:12px; color:#888; border:1px solid #ddd;\">ESC</kbd>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!-- Results Container -->\r\n");
      out.write("                    <div id=\"globalSearchResults\" style=\"max-height:460px; overflow-y:auto; padding:8px 0;\">\r\n");
      out.write("                        <div style=\"text-align:center; padding:40px 20px; color:#aaa;\">\r\n");
      out.write("                            <i class=\"fas fa-search\" style=\"font-size:40px; margin-bottom:12px; opacity:0.3;\"></i>\r\n");
      out.write("                            <p style=\"margin:0;\">Nhập từ khóa để bắt đầu tìm kiếm...</p>\r\n");
      out.write("                            <p style=\"margin:4px 0 0; font-size:13px; color:#ccc;\">Tìm theo tên, email, mã đơn hàng, ID...</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!-- Footer -->\r\n");
      out.write("                    <div style=\"padding:10px 24px; border-top:1px solid #eee; display:flex; justify-content:space-between; align-items:center; background:#fafafa;\">\r\n");
      out.write("                        <div style=\"display:flex; gap:16px; font-size:12px; color:#999;\">\r\n");
      out.write("                            <span><kbd style=\"background:#eee; padding:1px 5px; border-radius:3px; border:1px solid #ddd;\">↑↓</kbd> Chọn</span>\r\n");
      out.write("                            <span><kbd style=\"background:#eee; padding:1px 5px; border-radius:3px; border:1px solid #ddd;\">Enter</kbd> Mở</span>\r\n");
      out.write("                            <span><kbd style=\"background:#eee; padding:1px 5px; border-radius:3px; border:1px solid #ddd;\">Esc</kbd> Đóng</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <span style=\"font-size:12px; color:#ccc;\" id=\"globalSearchCount\"></span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <script>\r\n");
      out.write("            // ===== GLOBAL SEARCH LOGIC =====\r\n");
      out.write("            let searchTimer = null;\r\n");
      out.write("\r\n");
      out.write("            function openGlobalSearch() {\r\n");
      out.write("                document.getElementById('globalSearchOverlay').style.display = 'block';\r\n");
      out.write("                setTimeout(() => document.getElementById('globalSearchInput').focus(), 100);\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            function closeGlobalSearch() {\r\n");
      out.write("                document.getElementById('globalSearchOverlay').style.display = 'none';\r\n");
      out.write("                document.getElementById('globalSearchInput').value = '';\r\n");
      out.write("                document.getElementById('globalSearchResults').innerHTML =\r\n");
      out.write("                    '<div style=\"text-align:center; padding:40px 20px; color:#aaa;\">' +\r\n");
      out.write("                    '<i class=\"fas fa-search\" style=\"font-size:40px; margin-bottom:12px; opacity:0.3;\"></i>' +\r\n");
      out.write("                    '<p style=\"margin:0;\">Nhập từ khóa để bắt đầu tìm kiếm...</p></div>';\r\n");
      out.write("                document.getElementById('globalSearchCount').textContent = '';\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            function debounceSearch(query) {\r\n");
      out.write("                clearTimeout(searchTimer);\r\n");
      out.write("                if (query.trim().length < 2) {\r\n");
      out.write("                    document.getElementById('globalSearchResults').innerHTML =\r\n");
      out.write("                        '<div style=\"text-align:center; padding:40px 20px; color:#aaa;\">' +\r\n");
      out.write("                        '<i class=\"fas fa-search\" style=\"font-size:40px; margin-bottom:12px; opacity:0.3;\"></i>' +\r\n");
      out.write("                        '<p style=\"margin:0;\">Nhập ít nhất 2 ký tự...</p></div>';\r\n");
      out.write("                    document.getElementById('globalSearchCount').textContent = '';\r\n");
      out.write("                    return;\r\n");
      out.write("                }\r\n");
      out.write("                // Loading state\r\n");
      out.write("                document.getElementById('globalSearchResults').innerHTML =\r\n");
      out.write("                    '<div style=\"text-align:center; padding:40px 20px; color:#aaa;\">' +\r\n");
      out.write("                    '<i class=\"fas fa-spinner fa-spin\" style=\"font-size:24px;\"></i>' +\r\n");
      out.write("                    '<p style=\"margin:8px 0 0;\">Đang tìm kiếm...</p></div>';\r\n");
      out.write("\r\n");
      out.write("                searchTimer = setTimeout(() => performSearch(query), 300);\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            function performSearch(query) {\r\n");
      out.write("                fetch('admin-search?q=' + encodeURIComponent(query))\r\n");
      out.write("                    .then(r => r.json())\r\n");
      out.write("                    .then(data => renderResults(data))\r\n");
      out.write("                    .catch(err => {\r\n");
      out.write("                        document.getElementById('globalSearchResults').innerHTML =\r\n");
      out.write("                            '<div style=\"text-align:center; padding:40px 20px; color:#f44336;\">' +\r\n");
      out.write("                            '<i class=\"fas fa-exclamation-triangle\" style=\"font-size:24px;\"></i>' +\r\n");
      out.write("                            '<p style=\"margin:8px 0 0;\">Lỗi kết nối. Thử lại sau.</p></div>';\r\n");
      out.write("                    });\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            function renderResults(data) {\r\n");
      out.write("                const r = data.results;\r\n");
      out.write("                let html = '';\r\n");
      out.write("                const icons = {products:'fa-box',users:'fa-users',orders:'fa-receipt',categories:'fa-tags'};\r\n");
      out.write("                const labels = {products:'Sản Phẩm',users:'Người Dùng',orders:'Đơn Hàng',categories:'Danh Mục'};\r\n");
      out.write("                const colors = {products:'#ee4d2d',users:'#2196f3',orders:'#4caf50',categories:'#ff9800'};\r\n");
      out.write("\r\n");
      out.write("                for (const [type, items] of Object.entries(r)) {\r\n");
      out.write("                    if (items.length === 0) continue;\r\n");
      out.write("                    html += '<div style=\"padding:8px 24px 4px;\"><span style=\"font-size:11px; font-weight:700; color:' + colors[type] + '; text-transform:uppercase; letter-spacing:1px;\">' +\r\n");
      out.write("                        '<i class=\"fas ' + icons[type] + '\"></i> ' + labels[type] + ' (' + items.length + ')</span></div>';\r\n");
      out.write("\r\n");
      out.write("                    items.forEach(item => {\r\n");
      out.write("                        let subtitle = '';\r\n");
      out.write("                        let title = item.name || item.customer || '#' + item.id;\r\n");
      out.write("                        let icon = icons[type];\r\n");
      out.write("\r\n");
      out.write("                        if (type === 'products') {\r\n");
      out.write("                            subtitle = 'ID: ' + item.id + ' • Giá: ' + (item.price || 'N/A') + 'đ';\r\n");
      out.write("                        } else if (type === 'users') {\r\n");
      out.write("                            subtitle = (item.email || '') + (item.phone ? ' • ' + item.phone : '') + ' • ' + item.role;\r\n");
      out.write("                        } else if (type === 'orders') {\r\n");
      out.write("                            title = 'Đơn #' + item.id + ' — ' + item.customer;\r\n");
      out.write("                            subtitle = item.total + 'đ • ' + item.status + ' • ' + item.date;\r\n");
      out.write("                        } else if (type === 'categories') {\r\n");
      out.write("                            subtitle = 'ID: ' + item.id;\r\n");
      out.write("                        }\r\n");
      out.write("\r\n");
      out.write("                        html += '<a href=\"' + item.link + '\" style=\"display:flex; align-items:center; gap:12px; padding:10px 24px; cursor:pointer; text-decoration:none; color:inherit; transition:background 0.15s;\" ' +\r\n");
      out.write("                            'onmouseover=\"this.style.background=\\'#f5f5f5\\'\" onmouseout=\"this.style.background=\\'transparent\\'\">' +\r\n");
      out.write("                            '<div style=\"width:36px; height:36px; border-radius:8px; background:' + colors[type] + '15; display:flex; align-items:center; justify-content:center;\">' +\r\n");
      out.write("                            '<i class=\"fas ' + icon + '\" style=\"color:' + colors[type] + '; font-size:14px;\"></i></div>' +\r\n");
      out.write("                            '<div style=\"flex:1; min-width:0;\"><div style=\"font-size:14px; font-weight:500; white-space:nowrap; overflow:hidden; text-overflow:ellipsis;\">' + title + '</div>' +\r\n");
      out.write("                            '<div style=\"font-size:12px; color:#999; white-space:nowrap; overflow:hidden; text-overflow:ellipsis;\">' + subtitle + '</div></div>' +\r\n");
      out.write("                            '<i class=\"fas fa-arrow-right\" style=\"color:#ddd; font-size:12px;\"></i></a>';\r\n");
      out.write("                    });\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                if (data.total === 0) {\r\n");
      out.write("                    html = '<div style=\"text-align:center; padding:40px 20px; color:#aaa;\">' +\r\n");
      out.write("                        '<i class=\"fas fa-search\" style=\"font-size:40px; margin-bottom:12px; opacity:0.3;\"></i>' +\r\n");
      out.write("                        '<p style=\"margin:0;\">Không tìm thấy kết quả cho \"' + data.keyword + '\"</p></div>';\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                document.getElementById('globalSearchResults').innerHTML = html;\r\n");
      out.write("                document.getElementById('globalSearchCount').textContent = data.total + ' kết quả';\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            // Keyboard shortcut: Ctrl+K to open\r\n");
      out.write("            document.addEventListener('keydown', function(e) {\r\n");
      out.write("                if ((e.ctrlKey || e.metaKey) && e.key === 'k') {\r\n");
      out.write("                    e.preventDefault();\r\n");
      out.write("                    openGlobalSearch();\r\n");
      out.write("                }\r\n");
      out.write("                if (e.key === 'Escape') {\r\n");
      out.write("                    closeGlobalSearch();\r\n");
      out.write("                }\r\n");
      out.write("            });\r\n");
      out.write("            </script>\r\n");
      out.write("        </body>\r\n");
      out.write("\r\n");
      out.write("        </html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
