/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.19
 * Generated at: 2026-03-02 03:41:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.List;
import model.User;

public final class admin_005fusers_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/admin_sidebar.jsp", Long.valueOf(1772422274000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("model.User");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("        \r\n");
      out.write("            <!DOCTYPE html>\r\n");
      out.write("            <html lang=\"vi\">\r\n");
      out.write("\r\n");
      out.write("            <head>\r\n");
      out.write("                <meta charset=\"UTF-8\">\r\n");
      out.write("                <title>Quản lý Khách Hàng | Shopee Admin</title>\r\n");
      out.write("                <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("                <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css\">\r\n");
      out.write("                <link href=\"https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap\"\r\n");
      out.write("                    rel=\"stylesheet\">\r\n");
      out.write("                <style>\r\n");
      out.write("                    :root {\r\n");
      out.write("                        --shopee-primary: #ee4d2d;\r\n");
      out.write("                        --shopee-hover: #f05d40;\r\n");
      out.write("                        --sidebar-width: 260px;\r\n");
      out.write("                        --bg-color: #f5f5f5;\r\n");
      out.write("                        --card-shadow: 0 1px 3px rgba(0, 0, 0, 0.12), 0 1px 2px rgba(0, 0, 0, 0.24);\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("                    body {\r\n");
      out.write("                        background: var(--bg-color);\r\n");
      out.write("                        font-family: 'Inter', sans-serif;\r\n");
      out.write("                        overflow-x: hidden;\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("                    .sidebar {\r\n");
      out.write("                        height: 100vh;\r\n");
      out.write("                        background: #fff;\r\n");
      out.write("                        width: var(--sidebar-width);\r\n");
      out.write("                        position: fixed;\r\n");
      out.write("                        box-shadow: 2px 0 10px rgba(0, 0, 0, 0.05);\r\n");
      out.write("                        z-index: 100;\r\n");
      out.write("                    overflow-y: auto;\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("                    .sidebar-logo {\r\n");
      out.write("                        display: flex;\r\n");
      out.write("                        align-items: center;\r\n");
      out.write("                        justify-content: center;\r\n");
      out.write("                        padding: 20px 0;\r\n");
      out.write("                        border-bottom: 1px solid #eee;\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("                    .sidebar-logo h4 {\r\n");
      out.write("                        color: var(--shopee-primary);\r\n");
      out.write("                        font-weight: 700;\r\n");
      out.write("                        margin: 0;\r\n");
      out.write("                        font-size: 22px;\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("                    .nav-item {\r\n");
      out.write("                        padding: 5px 15px;\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("                    .sidebar a {\r\n");
      out.write("                        color: #555;\r\n");
      out.write("                        text-decoration: none;\r\n");
      out.write("                        padding: 12px 20px;\r\n");
      out.write("                        display: flex;\r\n");
      out.write("                        align-items: center;\r\n");
      out.write("                        border-radius: 8px;\r\n");
      out.write("                        font-weight: 500;\r\n");
      out.write("                        transition: all 0.2s ease;\r\n");
      out.write("                        margin-bottom: 5px;\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("                    .sidebar a i {\r\n");
      out.write("                        width: 30px;\r\n");
      out.write("                        font-size: 18px;\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("                    .sidebar a:hover {\r\n");
      out.write("                        background-color: #fef0ee;\r\n");
      out.write("                        color: var(--shopee-primary);\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("                    .sidebar a.active {\r\n");
      out.write("                        background-color: var(--shopee-primary);\r\n");
      out.write("                        color: #fff;\r\n");
      out.write("                        box-shadow: 0 4px 6px rgba(238, 77, 45, 0.2);\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("                    .main-content {\r\n");
      out.write("                        margin-left: var(--sidebar-width);\r\n");
      out.write("                        padding: 30px 40px;\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("                    .top-header {\r\n");
      out.write("                        display: flex;\r\n");
      out.write("                        justify-content: space-between;\r\n");
      out.write("                        align-items: center;\r\n");
      out.write("                        background: #fff;\r\n");
      out.write("                        padding: 15px 30px;\r\n");
      out.write("                        border-radius: 12px;\r\n");
      out.write("                        box-shadow: var(--card-shadow);\r\n");
      out.write("                        margin-bottom: 30px;\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("                    .content-box {\r\n");
      out.write("                        background: #fff;\r\n");
      out.write("                        padding: 25px;\r\n");
      out.write("                        border-radius: 12px;\r\n");
      out.write("                        box-shadow: var(--card-shadow);\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("                    .btn-shopee {\r\n");
      out.write("                        background-color: var(--shopee-primary);\r\n");
      out.write("                        color: white;\r\n");
      out.write("                        border: none;\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("                    .btn-shopee:hover {\r\n");
      out.write("                        background-color: var(--shopee-hover);\r\n");
      out.write("                        color: white;\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("                    .user-avatar {\r\n");
      out.write("                        width: 40px;\r\n");
      out.write("                        height: 40px;\r\n");
      out.write("                        border-radius: 50%;\r\n");
      out.write("                        display: flex;\r\n");
      out.write("                        align-items: center;\r\n");
      out.write("                        justify-content: center;\r\n");
      out.write("                        font-weight: 700;\r\n");
      out.write("                        font-size: 16px;\r\n");
      out.write("                        color: #fff;\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("                    .wallet-badge {\r\n");
      out.write("                        background: #e8f5e9;\r\n");
      out.write("                        color: #2e7d32;\r\n");
      out.write("                        font-weight: 600;\r\n");
      out.write("                        border-radius: 20px;\r\n");
      out.write("                        padding: 4px 12px;\r\n");
      out.write("                    }\r\n");
      out.write("                </style>\r\n");
      out.write("            </head>\r\n");
      out.write("\r\n");
      out.write("            <body>\r\n");
      out.write("                <!-- Sidebar -->\n");
      out.write("\r\n");
      out.write("                ");
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
 String currentPage = request.getServletPath(); 
      out.write("\r\n");
      out.write("<div class=\"sidebar d-flex flex-column\" style=\"overflow-y: auto;\">\r\n");
      out.write("    <div class=\"sidebar-logo\">\r\n");
      out.write("        <h4><i class=\"fas fa-shopping-bag me-1\"></i> Admin Panel</h4>\r\n");
      out.write("    </div>\r\n");
      out.write("    ");
 model.User s_admin = (model.User) session.getAttribute("account"); 
      out.write("\r\n");
      out.write("    <div class=\"mt-4 flex-grow-1\" style=\"overflow-y: auto; padding-bottom: 10px;\">\r\n");
      out.write("        ");
 if (s_admin != null && s_admin.hasPermission("VIEW_DASHBOARD")) { 
      out.write("\r\n");
      out.write("        <div class=\"nav-item\"><a href=\"admin\" class=\"");
      out.print( "/admin".equals(currentPage) ? "active" : "" );
      out.write("\"><i class=\"fas fa-chart-pie\"></i> T&#7893;ng Quan</a></div>\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("        ");
 if (s_admin != null && s_admin.hasPermission("MANAGE_ROLES")) { 
      out.write("\r\n");
      out.write("        <div class=\"nav-item\"><a href=\"admin-roles\" class=\"");
      out.print( "/admin-roles".equals(currentPage) ? "active" : "" );
      out.write("\"><i class=\"fas fa-user-shield\"></i> Nh&#243;m Quy&#7873;n</a></div>\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("        ");
 if (s_admin != null && s_admin.hasPermission("MANAGE_SYSTEM")) { 
      out.write("\r\n");
      out.write("        <div class=\"nav-item\"><a href=\"admin-import\" class=\"");
      out.print( "/admin-import".equals(currentPage) ? "active" : "" );
      out.write("\"><i class=\"fas fa-database\"></i> Qu&#7843;n l&#253; D&#7919; Li&#7879;u</a></div>\r\n");
      out.write("        <div class=\"nav-item\"><a href=\"admin-settings\" class=\"");
      out.print( "/admin-settings".equals(currentPage) ? "active" : "" );
      out.write("\"><i class=\"fas fa-cog\"></i> C&#7845;u H&#236;nh H&#7879; Th&#7889;ng</a></div>\r\n");
      out.write("        <div class=\"nav-item\"><a href=\"admin-generate\" class=\"");
      out.print( "/admin-generate".equals(currentPage) ? "active" : "" );
      out.write("\"><i class=\"fas fa-magic\"></i> T&#7841;o D&#7919; Li&#7879;u</a></div>\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("        ");
 if (s_admin != null && s_admin.hasPermission("MANAGE_PRODUCTS")) { 
      out.write("\r\n");
      out.write("        <div class=\"nav-item\"><a href=\"admin-products\" class=\"");
      out.print( "/admin-products".equals(currentPage) ? "active" : "" );
      out.write("\"><i class=\"fas fa-box-open\"></i> S&#7843;n Ph&#7849;m</a></div>\r\n");
      out.write("        <div class=\"nav-item\"><a href=\"admin-categories\" class=\"");
      out.print( "/admin-categories".equals(currentPage) ? "active" : "" );
      out.write("\"><i class=\"fas fa-tags\"></i> Danh M&#7909;c</a></div>\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("        ");
 if (s_admin != null && s_admin.hasPermission("MANAGE_ORDERS")) { 
      out.write("\r\n");
      out.write("        <div class=\"nav-item\"><a href=\"admin-orders\" class=\"");
      out.print( "/admin-orders".equals(currentPage) ? "active" : "" );
      out.write("\"><i class=\"fas fa-clipboard-list\"></i> &#272;&#417;n H&#224;ng</a></div>\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("        ");
 if (s_admin != null && s_admin.hasPermission("MANAGE_USERS")) { 
      out.write("\r\n");
      out.write("        <div class=\"nav-item\"><a href=\"admin-users\" class=\"");
      out.print( "/admin-users".equals(currentPage) ? "active" : "" );
      out.write("\"><i class=\"fas fa-users\"></i> Kh&#225;ch H&#224;ng</a></div>\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("        <div class=\"nav-item\"><a href=\"admin-reviews\" class=\"");
      out.print( "/admin-reviews".equals(currentPage) ? "active" : "" );
      out.write("\"><i class=\"fas fa-star-half-alt\"></i> X&#233;t Duy&#7879;t &#272;&#225;nh Gi&#225;</a></div>\r\n");
      out.write("        <div class=\"nav-item\"><a href=\"admin-alerts\" class=\"");
      out.print( "/admin-alerts".equals(currentPage) ? "active" : "" );
      out.write("\"><i class=\"fas fa-exclamation-triangle\"></i> C&#7843;nh B&#225;o B&#7845;t Th&#432;&#7901;ng</a></div>\r\n");
      out.write("        ");
 if (s_admin != null && s_admin.hasPermission("VIEW_AUDIT_LOGS")) { 
      out.write("\r\n");
      out.write("        <div class=\"nav-item\"><a href=\"admin-logs\" class=\"");
      out.print( "/admin-logs".equals(currentPage) ? "active" : "" );
      out.write("\"><i class=\"fas fa-history\"></i> Nh&#7853;t K&#253;</a></div>\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("        <div class=\"nav-item\"><a href=\"home\" target=\"_blank\"><i class=\"fas fa-globe\"></i> Truy C&#7853;p C&#7917;a H&#224;ng</a></div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"nav-item mb-4 border-top pt-3\">\r\n");
      out.write("        <a href=\"logout\" class=\"text-danger\"><i class=\"fas fa-sign-out-alt\"></i> &#272;&#259;ng Xu&#7845;t</a>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                <!-- Main Content -->\r\n");
      out.write("                <div class=\"main-content\">\r\n");
      out.write("                    <!-- Header -->\r\n");
      out.write("                    <div class=\"top-header\">\r\n");
      out.write("                        <div>\r\n");
      out.write("                            <h4 class=\"m-0 fw-bold text-dark\">Quản Lý Khách Hàng</h4>\r\n");
      out.write("                            <small class=\"text-muted\">Danh sách và thông tin người dùng</small>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"d-flex align-items-center gap-2 border-start ps-3\">\r\n");
      out.write("                            <img src=\"https://ui-avatars.com/api/?name=Admin&background=ee4d2d&color=fff&rounded=true\"\r\n");
      out.write("                                width=\"45\">\r\n");
      out.write("                            <div class=\"d-flex flex-column\">\r\n");
      out.write("                                <span class=\"fw-bold\" style=\"font-size: 14px;\">Super Admin</span>\r\n");
      out.write("                                <span class=\"text-muted\" style=\"font-size: 12px;\">Quản trị viên</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    ");
 if (session.getAttribute("successMessage") != null) { 
      out.write("\r\n");
      out.write("                        <div class=\"alert alert-success alert-dismissible fade show\" role=\"alert\">\r\n");
      out.write("                            <i class=\"fas fa-check-circle me-2\"></i> ");
      out.print( session.getAttribute("successMessage") );
      out.write("\r\n");
      out.write("                            <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"alert\" aria-label=\"Close\"></button>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        ");
 session.removeAttribute("successMessage"); 
      out.write("\r\n");
      out.write("                    ");
 } 
      out.write("\r\n");
      out.write("                    \r\n");
      out.write("                    ");
 if (session.getAttribute("errorMessage") != null) { 
      out.write("\r\n");
      out.write("                        <div class=\"alert alert-danger alert-dismissible fade show\" role=\"alert\">\r\n");
      out.write("                            <i class=\"fas fa-exclamation-triangle me-2\"></i> ");
      out.print( session.getAttribute("errorMessage") );
      out.write("\r\n");
      out.write("                            <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"alert\" aria-label=\"Close\"></button>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        ");
 session.removeAttribute("errorMessage"); 
      out.write("\r\n");
      out.write("                    ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("                    <!-- Content Box -->\r\n");
      out.write("                    <div class=\"content-box\">\r\n");
      out.write("                        <div class=\"d-flex justify-content-between align-items-center mb-4\">\r\n");
      out.write("                            <h5 class=\"fw-bold m-0 text-dark\"><i class=\"fas fa-users me-2 text-muted\"></i>\r\n");
      out.write("                                ");
 if (request.getAttribute("isTrash") != null && (Boolean) request.getAttribute("isTrash")) { 
      out.write("\r\n");
      out.write("                                    Thùng rác khách hàng\r\n");
      out.write("                                ");
 } else { 
      out.write("\r\n");
      out.write("                                    Danh sách khách hàng\r\n");
      out.write("                                ");
 } 
      out.write("\r\n");
      out.write("                            </h5>\r\n");
      out.write("                            <div class=\"d-flex gap-2 align-items-center\">\r\n");
      out.write("                                <span class=\"badge bg-secondary fs-6\">\r\n");
      out.write("                                    ");
 List<User> users = (List<User>) request.getAttribute("users");
                                            out.print(users != null ? users.size() : 0);
                                            
      out.write(" người dùng\r\n");
      out.write("                                </span>\r\n");
      out.write("                                ");
 if (request.getAttribute("isTrash") != null && (Boolean) request.getAttribute("isTrash")) { 
      out.write("\r\n");
      out.write("                                    <a href=\"admin-users\" class=\"btn btn-secondary btn-sm shadow-sm ms-2\">\r\n");
      out.write("                                        <i class=\"fas fa-arrow-left me-1\"></i> Quay lại\r\n");
      out.write("                                    </a>\r\n");
      out.write("                                ");
 } else { 
      out.write("\r\n");
      out.write("                                    <a href=\"admin-users?action=view_trash\" class=\"btn btn-warning btn-sm shadow-sm ms-2\">\r\n");
      out.write("                                        <i class=\"fas fa-trash-alt me-1\"></i> Xem Thùng Rác\r\n");
      out.write("                                    </a>\r\n");
      out.write("                                ");
 } 
      out.write("\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <!-- Bulk Actions -->\r\n");
      out.write("                        <div class=\"bulk-actions mb-4\" style=\"display: none;\" id=\"bulk-action-bar\">\r\n");
      out.write("                            <span class=\"me-2 text-muted fw-medium\"><span id=\"selected-count\">0</span> khách hàng đã chọn</span>\r\n");
      out.write("                            ");
 if (request.getAttribute("isTrash") != null && (Boolean) request.getAttribute("isTrash")) { 
      out.write("\r\n");
      out.write("                                <button type=\"button\" class=\"btn btn-outline-success shadow-sm\" onclick=\"submitBulkAction('bulk_restore')\">\r\n");
      out.write("                                    <i class=\"fas fa-undo me-1\"></i> Khôi phục mục chọn\r\n");
      out.write("                                </button>\r\n");
      out.write("                                <button type=\"button\" class=\"btn btn-danger shadow-sm ms-2\" onclick=\"submitBulkAction('bulk_delete_permanent')\">\r\n");
      out.write("                                    <i class=\"fas fa-trash-alt me-1\"></i> Xóa vĩnh viễn mục chọn\r\n");
      out.write("                                </button>\r\n");
      out.write("                            ");
 } else { 
      out.write("\r\n");
      out.write("                                <button type=\"button\" class=\"btn btn-outline-danger shadow-sm\" onclick=\"submitBulkAction('bulk_delete')\">\r\n");
      out.write("                                    <i class=\"fas fa-user-times me-1\"></i> Cấm mục chọn\r\n");
      out.write("                                </button>\r\n");
      out.write("                            ");
 } 
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <!-- Main Table Form -->\r\n");
      out.write("                        <form id=\"bulkForm\" action=\"admin-users\" method=\"POST\">\r\n");
      out.write("                            <input type=\"hidden\" name=\"action\" id=\"bulk-action-input\" value=\"\">\r\n");
      out.write("                        <div class=\"table-responsive\">\r\n");
      out.write("                            <table class=\"table table-hover border align-middle\">\r\n");
      out.write("                                <thead class=\"table-light\">\r\n");
      out.write("                                    <tr>\r\n");
      out.write("                                        <th width=\"40\" class=\"text-center\">\r\n");
      out.write("                                            <input class=\"form-check-input\" type=\"checkbox\" id=\"selectAll\">\r\n");
      out.write("                                        </th>\r\n");
      out.write("                                        <th width=\"60\">ID</th>\r\n");
      out.write("                                        <th>Tên Khách Hàng</th>\r\n");
      out.write("                                        <th>Email</th>\r\n");
      out.write("                                        <th>Số Điện Thoại</th>\r\n");
      out.write("                                        <th width=\"140\" class=\"text-end\">Số Dư Ví</th>\r\n");
      out.write("                                        <th width=\"100\" class=\"text-center\">Vai Trò</th>\r\n");
      out.write("                                        <th width=\"120\" class=\"text-center\">Hành Động</th>\r\n");
      out.write("                                    </tr>\r\n");
      out.write("                                </thead>\r\n");
      out.write("                                <tbody>\r\n");
      out.write("                                    ");
 String[]
                                        colors={"#ee4d2d","#007bff","#28a745","#6f42c1","#fd7e14","#20c997","#e83e8c"};
                                        if(users !=null) { int idx=0; for(User u : users) { String color=colors[idx %
                                        colors.length]; String initials="" ; if(u.getFullName() !=null &&
                                        !u.getFullName().isEmpty()) { String[]
                                        parts=u.getFullName().trim().split("\\s+"); initials=parts.length> 1
                                        ? ("" + parts[0].charAt(0) + parts[parts.length-1].charAt(0)).toUpperCase()
                                        : ("" + parts[0].charAt(0)).toUpperCase();
                                        }
                                        idx++;
                                        
      out.write("\r\n");
      out.write("                                        <tr>\r\n");
      out.write("                                            <td class=\"text-center\">\r\n");
      out.write("                                                <input class=\"form-check-input row-checkbox\" type=\"checkbox\" name=\"selectedIds\" value=\"");
      out.print( u.getId() );
      out.write("\">\r\n");
      out.write("                                            </td>\r\n");
      out.write("                                            <td class=\"fw-bold text-muted\">#");
      out.print( u.getId() );
      out.write("\r\n");
      out.write("                                            </td>\r\n");
      out.write("                                            <td>\r\n");
      out.write("                                                <div class=\"d-flex align-items-center gap-2\">\r\n");
      out.write("                                                    <div class=\"user-avatar\" style=\"background: ");
      out.print( color );
      out.write(";\">\r\n");
      out.write("                                                        ");
      out.print( initials );
      out.write("\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                    <span class=\"fw-medium\">\r\n");
      out.write("                                                        ");
      out.print( u.getFullName() !=null ? u.getFullName() : "N/A" );
      out.write("\r\n");
      out.write("                                                    </span>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </td>\r\n");
      out.write("                                            <td class=\"text-muted\">\r\n");
      out.write("                                                ");
      out.print( u.getEmail() !=null ? u.getEmail() : "N/A" );
      out.write("\r\n");
      out.write("                                            </td>\r\n");
      out.write("                                            <td>\r\n");
      out.write("                                                ");
      out.print( u.getPhone() !=null ? u.getPhone() : "N/A" );
      out.write("\r\n");
      out.write("                                            </td>\r\n");
      out.write("                                            <td class=\"text-end\">\r\n");
      out.write("                                                <span class=\"wallet-badge\">\r\n");
      out.write("                                                    ");
      out.print( String.format("%,.0f", u.getWallet()) );
      out.write(" đ\r\n");
      out.write("                                                </span>\r\n");
      out.write("                                            </td>\r\n");
      out.write("                                            <td class=\"text-center\">\r\n");
      out.write("                                                <span class=\"badge bg-info text-dark px-3 py-2\">\r\n");
      out.write("                                                    ");
      out.print( u.getRole() !=null ? u.getRole().toUpperCase() : "USER" );
      out.write("\r\n");
      out.write("                                                </span>\r\n");
      out.write("                                            </td>\r\n");
      out.write("                                            <td class=\"text-center\">\r\n");
      out.write("                                                ");
 if (request.getAttribute("isTrash") != null && (Boolean) request.getAttribute("isTrash")) { 
      out.write("\r\n");
      out.write("                                                    <form action=\"admin-users\" method=\"POST\" style=\"display:inline;\">\r\n");
      out.write("                                                        <input type=\"hidden\" name=\"action\" value=\"restore\">\r\n");
      out.write("                                                        <input type=\"hidden\" name=\"id\" value=\"");
      out.print( u.getId() );
      out.write("\">\r\n");
      out.write("                                                        <button type=\"submit\" class=\"btn btn-sm btn-outline-success shadow-sm mb-1\">\r\n");
      out.write("                                                            <i class=\"fas fa-undo\"></i> Khôi phục\r\n");
      out.write("                                                        </button>\r\n");
      out.write("                                                    </form>\r\n");
      out.write("                                                ");
 } else { 
      out.write("\r\n");
      out.write("                                                    <button type=\"button\" class=\"btn btn-sm btn-outline-primary shadow-sm mb-1\"\r\n");
      out.write("                                                            onclick=\"openAssignRoleModal(");
      out.print( u.getId() );
      out.write(',');
      out.write(' ');
      out.write('\'');
      out.print( u.getFullName().replace("'", "\\\\'") );
      out.write('\'');
      out.write(',');
      out.write(' ');
      out.print( u.getAdminRoleId() != null ? u.getAdminRoleId() : "0" );
      out.write(',');
      out.write(' ');
      out.write('\'');
      out.print( u.getRole() );
      out.write("')\">\r\n");
      out.write("                                                        <i class=\"fas fa-exchange-alt\"></i> Cấp/Thu Quyền\r\n");
      out.write("                                                    </button>\r\n");
      out.write("                                                    <form action=\"admin-users\" method=\"POST\" style=\"display:inline;\"\r\n");
      out.write("                                                        onsubmit=\"return confirm('Bạn có chắc chắn muốn xóa người dùng này?');\">\r\n");
      out.write("                                                        <input type=\"hidden\" name=\"action\" value=\"delete\">\r\n");
      out.write("                                                        <input type=\"hidden\" name=\"id\" value=\"");
      out.print( u.getId() );
      out.write("\">\r\n");
      out.write("                                                        <button type=\"submit\" class=\"btn btn-sm btn-outline-danger shadow-sm mb-1\">\r\n");
      out.write("                                                            <i class=\"fas fa-trash\"></i> Xóa\r\n");
      out.write("                                                        </button>\r\n");
      out.write("                                                    </form>\r\n");
      out.write("                                                ");
 } 
      out.write("\r\n");
      out.write("                                            </td>\r\n");
      out.write("                                        </tr>\r\n");
      out.write("                                        ");
 } } 
      out.write("\r\n");
      out.write("                                </tbody>\r\n");
      out.write("                            </table>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        </form>\r\n");
      out.write("\r\n");
      out.write("                        ");
 if(users==null || users.isEmpty()) { 
      out.write("\r\n");
      out.write("                            <div class=\"text-center py-5 text-muted\">\r\n");
      out.write("                                <i class=\"fas fa-users fa-3x mb-3\"></i>\r\n");
      out.write("                                <h5>Chưa có khách hàng nào</h5>\r\n");
      out.write("                                <p>Người dùng đăng ký sẽ hiển thị ở đây.</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            ");
 } 
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <!-- Assign Role Modal -->\r\n");
      out.write("                <div class=\"modal fade\" id=\"assignRoleModal\" tabindex=\"-1\" aria-hidden=\"true\">\r\n");
      out.write("                    <div class=\"modal-dialog\">\r\n");
      out.write("                        <div class=\"modal-content\">\r\n");
      out.write("                            <div class=\"modal-header\">\r\n");
      out.write("                                <h5 class=\"modal-title fw-bold\">Cấp/Thu Quyền <span id=\"assign-role-username\" class=\"text-primary\"></span></h5>\r\n");
      out.write("                                <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\" aria-label=\"Close\"></button>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <form action=\"admin-users\" method=\"POST\">\r\n");
      out.write("                                <div class=\"modal-body\">\r\n");
      out.write("                                    <input type=\"hidden\" name=\"action\" value=\"assign_role\">\r\n");
      out.write("                                    <input type=\"hidden\" name=\"id\" id=\"assign-role-id\">\r\n");
      out.write("                                    \r\n");
      out.write("                                    <div class=\"mb-3\">\r\n");
      out.write("                                        <label class=\"form-label fw-medium\">Chọn Vai Trò (Nhóm Quyền)</label>\r\n");
      out.write("                                        <select class=\"form-select\" name=\"admin_role_id\" id=\"assign-role-select\">\r\n");
      out.write("                                            <option value=\"0\">-- Khách Hàng (Tước quyền Admin) --</option>\r\n");
      out.write("                                            ");
 
                                            List<model.Role> adminRoles = (List<model.Role>) request.getAttribute("adminRoles");
                                            if (adminRoles != null) {
                                                for (model.Role r : adminRoles) {
                                            
      out.write("\r\n");
      out.write("                                            <option value=\"");
      out.print( r.getId() );
      out.write('"');
      out.write('>');
      out.print( r.getName() );
      out.write(' ');
      out.write('-');
      out.write(' ');
      out.print( r.getDescription() );
      out.write("</option>\r\n");
      out.write("                                            ");
  }
                                            } 
      out.write("\r\n");
      out.write("                                        </select>\r\n");
      out.write("                                        <div class=\"form-text mt-2 text-danger\">Lưu ý: Nếu chọn \"Khách Hàng\", người dùng sẽ bị tước mọi quyền quản trị hệ thống.</div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"modal-footer bg-light\">\r\n");
      out.write("                                    <button type=\"button\" class=\"btn btn-light border\" data-bs-dismiss=\"modal\">Hủy</button>\r\n");
      out.write("                                    <button type=\"submit\" class=\"btn btn-shopee\">Áp dụng</button>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </form>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("                <script>\r\n");
      out.write("                    function openAssignRoleModal(id, name, roleId, currentRole) {\r\n");
      out.write("                        document.getElementById('assign-role-id').value = id;\r\n");
      out.write("                        document.getElementById('assign-role-username').innerText = name;\r\n");
      out.write("                        \r\n");
      out.write("                        let select = document.getElementById('assign-role-select');\r\n");
      out.write("                        if (currentRole.toLowerCase() === 'admin' && roleId > 0) {\r\n");
      out.write("                            select.value = roleId;\r\n");
      out.write("                        } else {\r\n");
      out.write("                            select.value = '0';\r\n");
      out.write("                        }\r\n");
      out.write("                        \r\n");
      out.write("                        var assignRoleModal = new bootstrap.Modal(document.getElementById('assignRoleModal'));\r\n");
      out.write("                        assignRoleModal.show();\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("                    // --- Bulk Actions Script ---\r\n");
      out.write("                    document.addEventListener(\"DOMContentLoaded\", function () {\r\n");
      out.write("                        const selectAllCheckbox = document.getElementById('selectAll');\r\n");
      out.write("                        const rowCheckboxes = document.querySelectorAll('.row-checkbox');\r\n");
      out.write("                        const bulkActionBar = document.getElementById('bulk-action-bar');\r\n");
      out.write("                        const selectedCountSpan = document.getElementById('selected-count');\r\n");
      out.write("\r\n");
      out.write("                        function updateBulkActionVisibility() {\r\n");
      out.write("                            const checkedCount = document.querySelectorAll('.row-checkbox:checked').length;\r\n");
      out.write("                            selectedCountSpan.textContent = checkedCount;\r\n");
      out.write("                            if (checkedCount > 0) {\r\n");
      out.write("                                bulkActionBar.style.display = 'block';\r\n");
      out.write("                            } else {\r\n");
      out.write("                                bulkActionBar.style.display = 'none';\r\n");
      out.write("                                selectAllCheckbox.checked = false;\r\n");
      out.write("                            }\r\n");
      out.write("                        }\r\n");
      out.write("\r\n");
      out.write("                        if (selectAllCheckbox) {\r\n");
      out.write("                            selectAllCheckbox.addEventListener('change', function () {\r\n");
      out.write("                                rowCheckboxes.forEach(cb => {\r\n");
      out.write("                                    cb.checked = selectAllCheckbox.checked;\r\n");
      out.write("                                });\r\n");
      out.write("                                updateBulkActionVisibility();\r\n");
      out.write("                            });\r\n");
      out.write("                        }\r\n");
      out.write("\r\n");
      out.write("                        rowCheckboxes.forEach(cb => {\r\n");
      out.write("                            cb.addEventListener('change', function () {\r\n");
      out.write("                                const allChecked = document.querySelectorAll('.row-checkbox:checked').length === rowCheckboxes.length;\r\n");
      out.write("                                selectAllCheckbox.checked = allChecked;\r\n");
      out.write("                                updateBulkActionVisibility();\r\n");
      out.write("                            });\r\n");
      out.write("                        });\r\n");
      out.write("                    });\r\n");
      out.write("\r\n");
      out.write("                    function submitBulkAction(actionName) {\r\n");
      out.write("                        const count = document.querySelectorAll('.row-checkbox:checked').length;\r\n");
      out.write("                        if (count === 0) return;\r\n");
      out.write("                        \r\n");
      out.write("                        let msg = \"\";\r\n");
      out.write("                        if(actionName === 'bulk_delete') msg = \"Bạn có chắc chắn muốn cấm (Ban) \" + count + \" người dùng đã chọn vào thùng rác không?\";\r\n");
      out.write("                        else if(actionName === 'bulk_delete_permanent') msg = \"⚠️ CẢNH BÁO: Rất nhiều đơn hàng phụ thuộc vào User ID. Việc XÓA VĨNH VIỄN \" + count + \" tài khoản này có thể gây lỗi. Phê duyệt?\";\r\n");
      out.write("                        else if(actionName === 'bulk_restore') msg = \"Khôi phục \" + count + \" người dùng đã chọn?\";\r\n");
      out.write("\r\n");
      out.write("                        if (confirm(msg)) {\r\n");
      out.write("                            document.getElementById('bulk-action-input').value = actionName;\r\n");
      out.write("                            document.getElementById('bulkForm').submit();\r\n");
      out.write("                        }\r\n");
      out.write("                    }\r\n");
      out.write("                </script>\r\n");
      out.write("            </body>\r\n");
      out.write("\r\n");
      out.write("            </html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
