/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.19
 * Generated at: 2026-03-02 03:41:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class admin_005fimport_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/admin_sidebar.jsp", Long.valueOf(1772422274000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    <!DOCTYPE html>\r\n");
      out.write("    <html lang=\"vi\">\r\n");
      out.write("\r\n");
      out.write("    <head>\r\n");
      out.write("        <meta charset=\"UTF-8\">\r\n");
      out.write("        <title>Import Dữ Liệu | Shopee Admin</title>\r\n");
      out.write("        <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css\">\r\n");
      out.write("        <link href=\"https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("        <style>\r\n");
      out.write("            :root {\r\n");
      out.write("                --shopee-primary: #ee4d2d;\r\n");
      out.write("                --sidebar-width: 260px;\r\n");
      out.write("                --bg-color: #f5f5f5;\r\n");
      out.write("                --card-shadow: 0 1px 3px rgba(0, 0, 0, 0.12), 0 1px 2px rgba(0, 0, 0, 0.24);\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            body {\r\n");
      out.write("                background: var(--bg-color);\r\n");
      out.write("                font-family: 'Inter', sans-serif;\r\n");
      out.write("                overflow-x: hidden;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            /* Sidebar */\r\n");
      out.write("            .sidebar {\r\n");
      out.write("                height: 100vh;\r\n");
      out.write("                background: #ffffff;\r\n");
      out.write("                width: var(--sidebar-width);\r\n");
      out.write("                position: fixed;\r\n");
      out.write("                box-shadow: 2px 0 10px rgba(0, 0, 0, 0.05);\r\n");
      out.write("                z-index: 100;\r\n");
      out.write("                    overflow-y: auto;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .sidebar-logo {\r\n");
      out.write("                display: flex;\r\n");
      out.write("                align-items: center;\r\n");
      out.write("                justify-content: center;\r\n");
      out.write("                padding: 20px 0;\r\n");
      out.write("                border-bottom: 1px solid #eee;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .sidebar-logo h4 {\r\n");
      out.write("                color: var(--shopee-primary);\r\n");
      out.write("                font-weight: 700;\r\n");
      out.write("                margin: 0;\r\n");
      out.write("                font-size: 22px;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .nav-item {\r\n");
      out.write("                padding: 5px 15px;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .sidebar a {\r\n");
      out.write("                color: #555;\r\n");
      out.write("                text-decoration: none;\r\n");
      out.write("                padding: 12px 20px;\r\n");
      out.write("                display: flex;\r\n");
      out.write("                align-items: center;\r\n");
      out.write("                border-radius: 8px;\r\n");
      out.write("                font-weight: 500;\r\n");
      out.write("                transition: all 0.2s ease;\r\n");
      out.write("                margin-bottom: 5px;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .sidebar a i {\r\n");
      out.write("                width: 30px;\r\n");
      out.write("                font-size: 18px;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .sidebar a:hover {\r\n");
      out.write("                background-color: #fef0ee;\r\n");
      out.write("                color: var(--shopee-primary);\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .sidebar a.active {\r\n");
      out.write("                background-color: var(--shopee-primary);\r\n");
      out.write("                color: #ffffff;\r\n");
      out.write("                box-shadow: 0 4px 6px rgba(238, 77, 45, 0.2);\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            /* Main Content */\r\n");
      out.write("            .main-content {\r\n");
      out.write("                margin-left: var(--sidebar-width);\r\n");
      out.write("                padding: 30px 40px;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .top-header {\r\n");
      out.write("                display: flex;\r\n");
      out.write("                justify-content: space-between;\r\n");
      out.write("                align-items: center;\r\n");
      out.write("                background: #fff;\r\n");
      out.write("                padding: 15px 30px;\r\n");
      out.write("                border-radius: 12px;\r\n");
      out.write("                box-shadow: var(--card-shadow);\r\n");
      out.write("                margin-bottom: 30px;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .card-custom {\r\n");
      out.write("                border: none;\r\n");
      out.write("                border-radius: 12px;\r\n");
      out.write("                background: #fff;\r\n");
      out.write("                box-shadow: var(--card-shadow);\r\n");
      out.write("                overflow: hidden;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .btn-shopee {\r\n");
      out.write("                background: linear-gradient(90deg, #ff7b54, #ee4d2d);\r\n");
      out.write("                color: #fff;\r\n");
      out.write("                font-weight: 600;\r\n");
      out.write("                border: none;\r\n");
      out.write("                box-shadow: 0 4px 6px rgba(238, 77, 45, 0.3);\r\n");
      out.write("                transition: transform 0.2s ease;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .btn-shopee:hover {\r\n");
      out.write("                background: linear-gradient(90deg, #ee4d2d, #ff7b54);\r\n");
      out.write("                color: #fff;\r\n");
      out.write("                transform: translateY(-2px);\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .log-box {\r\n");
      out.write("                background: #212529;\r\n");
      out.write("                color: #0dcf45;\r\n");
      out.write("                font-family: 'Consolas', monospace;\r\n");
      out.write("                height: 350px;\r\n");
      out.write("                overflow-y: scroll;\r\n");
      out.write("                padding: 20px;\r\n");
      out.write("                border-radius: 0 0 12px 12px;\r\n");
      out.write("                font-size: 14px;\r\n");
      out.write("                line-height: 1.6;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .log-box::-webkit-scrollbar {\r\n");
      out.write("                width: 8px;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .log-box::-webkit-scrollbar-thumb {\r\n");
      out.write("                background: #495057;\r\n");
      out.write("                border-radius: 4px;\r\n");
      out.write("            }\r\n");
      out.write("        </style>\r\n");
      out.write("    </head>\r\n");
      out.write("\r\n");
      out.write("    <body>\r\n");
      out.write("\r\n");
      out.write("        <!-- Sidebar -->\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        ");
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
 String currentPage = request.getServletPath(); 
      out.write("\r\n");
      out.write("<div class=\"sidebar d-flex flex-column\" style=\"overflow-y: auto;\">\r\n");
      out.write("    <div class=\"sidebar-logo\">\r\n");
      out.write("        <h4><i class=\"fas fa-shopping-bag me-1\"></i> Admin Panel</h4>\r\n");
      out.write("    </div>\r\n");
      out.write("    ");
 model.User s_admin = (model.User) session.getAttribute("account"); 
      out.write("\r\n");
      out.write("    <div class=\"mt-4 flex-grow-1\" style=\"overflow-y: auto; padding-bottom: 10px;\">\r\n");
      out.write("        ");
 if (s_admin != null && s_admin.hasPermission("VIEW_DASHBOARD")) { 
      out.write("\r\n");
      out.write("        <div class=\"nav-item\"><a href=\"admin\" class=\"");
      out.print( "/admin".equals(currentPage) ? "active" : "" );
      out.write("\"><i class=\"fas fa-chart-pie\"></i> T&#7893;ng Quan</a></div>\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("        ");
 if (s_admin != null && s_admin.hasPermission("MANAGE_ROLES")) { 
      out.write("\r\n");
      out.write("        <div class=\"nav-item\"><a href=\"admin-roles\" class=\"");
      out.print( "/admin-roles".equals(currentPage) ? "active" : "" );
      out.write("\"><i class=\"fas fa-user-shield\"></i> Nh&#243;m Quy&#7873;n</a></div>\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("        ");
 if (s_admin != null && s_admin.hasPermission("MANAGE_SYSTEM")) { 
      out.write("\r\n");
      out.write("        <div class=\"nav-item\"><a href=\"admin-import\" class=\"");
      out.print( "/admin-import".equals(currentPage) ? "active" : "" );
      out.write("\"><i class=\"fas fa-database\"></i> Qu&#7843;n l&#253; D&#7919; Li&#7879;u</a></div>\r\n");
      out.write("        <div class=\"nav-item\"><a href=\"admin-settings\" class=\"");
      out.print( "/admin-settings".equals(currentPage) ? "active" : "" );
      out.write("\"><i class=\"fas fa-cog\"></i> C&#7845;u H&#236;nh H&#7879; Th&#7889;ng</a></div>\r\n");
      out.write("        <div class=\"nav-item\"><a href=\"admin-generate\" class=\"");
      out.print( "/admin-generate".equals(currentPage) ? "active" : "" );
      out.write("\"><i class=\"fas fa-magic\"></i> T&#7841;o D&#7919; Li&#7879;u</a></div>\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("        ");
 if (s_admin != null && s_admin.hasPermission("MANAGE_PRODUCTS")) { 
      out.write("\r\n");
      out.write("        <div class=\"nav-item\"><a href=\"admin-products\" class=\"");
      out.print( "/admin-products".equals(currentPage) ? "active" : "" );
      out.write("\"><i class=\"fas fa-box-open\"></i> S&#7843;n Ph&#7849;m</a></div>\r\n");
      out.write("        <div class=\"nav-item\"><a href=\"admin-categories\" class=\"");
      out.print( "/admin-categories".equals(currentPage) ? "active" : "" );
      out.write("\"><i class=\"fas fa-tags\"></i> Danh M&#7909;c</a></div>\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("        ");
 if (s_admin != null && s_admin.hasPermission("MANAGE_ORDERS")) { 
      out.write("\r\n");
      out.write("        <div class=\"nav-item\"><a href=\"admin-orders\" class=\"");
      out.print( "/admin-orders".equals(currentPage) ? "active" : "" );
      out.write("\"><i class=\"fas fa-clipboard-list\"></i> &#272;&#417;n H&#224;ng</a></div>\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("        ");
 if (s_admin != null && s_admin.hasPermission("MANAGE_USERS")) { 
      out.write("\r\n");
      out.write("        <div class=\"nav-item\"><a href=\"admin-users\" class=\"");
      out.print( "/admin-users".equals(currentPage) ? "active" : "" );
      out.write("\"><i class=\"fas fa-users\"></i> Kh&#225;ch H&#224;ng</a></div>\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("        <div class=\"nav-item\"><a href=\"admin-reviews\" class=\"");
      out.print( "/admin-reviews".equals(currentPage) ? "active" : "" );
      out.write("\"><i class=\"fas fa-star-half-alt\"></i> X&#233;t Duy&#7879;t &#272;&#225;nh Gi&#225;</a></div>\r\n");
      out.write("        <div class=\"nav-item\"><a href=\"admin-alerts\" class=\"");
      out.print( "/admin-alerts".equals(currentPage) ? "active" : "" );
      out.write("\"><i class=\"fas fa-exclamation-triangle\"></i> C&#7843;nh B&#225;o B&#7845;t Th&#432;&#7901;ng</a></div>\r\n");
      out.write("        ");
 if (s_admin != null && s_admin.hasPermission("VIEW_AUDIT_LOGS")) { 
      out.write("\r\n");
      out.write("        <div class=\"nav-item\"><a href=\"admin-logs\" class=\"");
      out.print( "/admin-logs".equals(currentPage) ? "active" : "" );
      out.write("\"><i class=\"fas fa-history\"></i> Nh&#7853;t K&#253;</a></div>\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("        <div class=\"nav-item\"><a href=\"home\" target=\"_blank\"><i class=\"fas fa-globe\"></i> Truy C&#7853;p C&#7917;a H&#224;ng</a></div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"nav-item mb-4 border-top pt-3\">\r\n");
      out.write("        <a href=\"logout\" class=\"text-danger\"><i class=\"fas fa-sign-out-alt\"></i> &#272;&#259;ng Xu&#7845;t</a>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <!-- Main Content -->\r\n");
      out.write("        <div class=\"main-content\">\r\n");
      out.write("            <!-- Header -->\r\n");
      out.write("            <div class=\"top-header\">\r\n");
      out.write("                <div>\r\n");
      out.write("                    <h4 class=\"m-0 fw-bold text-dark\">Quản Lý Dữ Liệu Hệ Thống</h4>\r\n");
      out.write("                    <small class=\"text-muted\">Import File CSV và Khôi Phục CSDL</small>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"d-flex align-items-center gap-3\">\r\n");
      out.write("                    <div class=\"d-flex align-items-center gap-2\">\r\n");
      out.write("                        <img src=\"https://ui-avatars.com/api/?name=Admin&background=ee4d2d&color=fff&rounded=true\"\r\n");
      out.write("                            width=\"45\">\r\n");
      out.write("                        <div class=\"d-flex flex-column\">\r\n");
      out.write("                            <span class=\"fw-bold\" style=\"font-size: 14px;\">Super Admin</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- Action Card -->\r\n");
      out.write("            <div class=\"card card-custom mb-4\">\r\n");
      out.write("                <div class=\"card-header bg-danger text-white fw-bold py-3\"><i\r\n");
      out.write("                        class=\"fas fa-exclamation-triangle me-2\"></i> RESET DATABASE (MIGRATION)</div>\r\n");
      out.write("                <div class=\"card-body text-center py-5\">\r\n");
      out.write("                    <div class=\"mb-4\">\r\n");
      out.write("                        <i class=\"fas fa-cloud-upload-alt text-muted mb-3\" style=\"font-size: 50px;\"></i>\r\n");
      out.write("                        <h5 class=\"fw-bold\">Khôi phục Dữ liệu Mẫu (10.000+ Rows)</h5>\r\n");
      out.write("                        <p class=\"text-muted mx-auto\" style=\"max-width: 600px;\">\r\n");
      out.write("                            Hệ thống sẽ <strong>xóa toàn bộ</strong> thông tin cũ trong Database và đọc lại thư mục Data\r\n");
      out.write("                            để nhúng bản ghi CSV.\r\n");
      out.write("                            <br><span class=\"text-danger fw-bold\">Lưu ý: Hành động này KHÔNG THỂ HOÀN TÁC!</span>\r\n");
      out.write("                        </p>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <form action=\"admin-import\" method=\"post\" id=\"importForm\">\r\n");
      out.write("                        <button type=\"button\" id=\"btn\" class=\"btn btn-shopee btn-lg px-5 py-2 rounded-pill\"\r\n");
      out.write("                            onclick=\"loading()\">\r\n");
      out.write("                            <i class=\"fas fa-sync-alt me-2\"></i> BẮT ĐẦU IMPORT NGAY\r\n");
      out.write("                        </button>\r\n");
      out.write("                    </form>\r\n");
      out.write("\r\n");
      out.write("                    <div id=\"load\" class=\"d-none mt-4\">\r\n");
      out.write("                        <div class=\"spinner-border text-danger\" role=\"status\" style=\"width: 3rem; height: 3rem;\"></div>\r\n");
      out.write("                        <h5 class=\"mt-3 fw-bold text-danger\">Đang xử lý dữ liệu lớn... Cấm đóng trình duyệt!</h5>\r\n");
      out.write("                        <small class=\"text-muted\">Việc này có thể tốn từ 1 đến 5 phút tùy hiệu năng server.</small>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- Log Card -->\r\n");
      out.write("            <div class=\"card card-custom\">\r\n");
      out.write("                <div\r\n");
      out.write("                    class=\"card-header bg-dark text-white fw-bold py-3 d-flex justify-content-between align-items-center\">\r\n");
      out.write("                    <span><i class=\"fas fa-terminal me-2\"></i> SYSTEM LOGS (CONSOLE)</span>\r\n");
      out.write("                    <span class=\"badge bg-success\">LIVE</span>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"card-body p-0\">\r\n");
      out.write("                    <div class=\"log-box\">\r\n");
      out.write("                        ");
 if(request.getAttribute("logs") !=null) { 
      out.write("\r\n");
      out.write("                            ");
      out.print( request.getAttribute("logs").toString().replace("\n", "<br>" ) );
      out.write("\r\n");
      out.write("                                ");
 } else { 
      out.write("\r\n");
      out.write("                                    <span class=\"text-muted\">> System loaded. Ready to receive commands...</span><br>\r\n");
      out.write("                                    <span class=\"text-muted\">> Please execute Action [IMPORT] to view logs.</span>\r\n");
      out.write("                                    ");
 } 
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"text-center mt-4 text-muted\">\r\n");
      out.write("                <small>&copy; 2026 Designed for Shopee Clone Administrators.</small>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <script>\r\n");
      out.write("            function loading() {\r\n");
      out.write("                var btn = document.getElementById('btn');\r\n");
      out.write("                var load = document.getElementById('load');\r\n");
      out.write("                var form = document.getElementById('importForm');\r\n");
      out.write("\r\n");
      out.write("                if (confirm(\"Bạn có chắc chắn muốn XÓA SẠCH dữ liệu cũ và MIGRATION toàn bộ dữ liệu mẫu không? Hành động này nguy hiểm!\")) {\r\n");
      out.write("                    btn.classList.add('d-none');\r\n");
      out.write("                    load.classList.remove('d-none');\r\n");
      out.write("                    form.submit(); // Bấm Yes mới nộp\r\n");
      out.write("                }\r\n");
      out.write("            }\r\n");
      out.write("        </script>\r\n");
      out.write("    </body>\r\n");
      out.write("\r\n");
      out.write("    </html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
