/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.19
 * Generated at: 2026-03-01 14:34:54 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class admin_005fotp_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    <!DOCTYPE html>\r\n");
      out.write("    <html lang=\"vi\">\r\n");
      out.write("\r\n");
      out.write("    <head>\r\n");
      out.write("        <meta charset=\"UTF-8\">\r\n");
      out.write("        <title>Xác thực Admin | Shopee Clone</title>\r\n");
      out.write("        <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css\">\r\n");
      out.write("        <link href=\"https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("        <style>\r\n");
      out.write("            * {\r\n");
      out.write("                margin: 0;\r\n");
      out.write("                padding: 0;\r\n");
      out.write("                box-sizing: border-box;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            body {\r\n");
      out.write("                font-family: 'Inter', sans-serif;\r\n");
      out.write("                background: linear-gradient(135deg, #ee4d2d 0%, #ff7b54 50%, #ee4d2d 100%);\r\n");
      out.write("                min-height: 100vh;\r\n");
      out.write("                display: flex;\r\n");
      out.write("                align-items: center;\r\n");
      out.write("                justify-content: center;\r\n");
      out.write("                overflow: hidden;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            /* Animated background particles */\r\n");
      out.write("            .bg-particles {\r\n");
      out.write("                position: fixed;\r\n");
      out.write("                top: 0;\r\n");
      out.write("                left: 0;\r\n");
      out.write("                right: 0;\r\n");
      out.write("                bottom: 0;\r\n");
      out.write("                pointer-events: none;\r\n");
      out.write("                z-index: 0;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .bg-particles::before,\r\n");
      out.write("            .bg-particles::after {\r\n");
      out.write("                content: '';\r\n");
      out.write("                position: absolute;\r\n");
      out.write("                border-radius: 50%;\r\n");
      out.write("                background: rgba(255, 255, 255, 0.05);\r\n");
      out.write("                animation: float 6s ease-in-out infinite;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .bg-particles::before {\r\n");
      out.write("                width: 300px;\r\n");
      out.write("                height: 300px;\r\n");
      out.write("                top: -50px;\r\n");
      out.write("                right: -50px;\r\n");
      out.write("                animation-delay: 0s;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .bg-particles::after {\r\n");
      out.write("                width: 200px;\r\n");
      out.write("                height: 200px;\r\n");
      out.write("                bottom: -30px;\r\n");
      out.write("                left: -30px;\r\n");
      out.write("                animation-delay: 3s;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            @keyframes float {\r\n");
      out.write("\r\n");
      out.write("                0%,\r\n");
      out.write("                100% {\r\n");
      out.write("                    transform: translateY(0) scale(1);\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                50% {\r\n");
      out.write("                    transform: translateY(-30px) scale(1.05);\r\n");
      out.write("                }\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            /* Main card */\r\n");
      out.write("            .otp-card {\r\n");
      out.write("                background: #ffffff;\r\n");
      out.write("                border-radius: 20px;\r\n");
      out.write("                box-shadow: 0 25px 60px rgba(0, 0, 0, 0.2);\r\n");
      out.write("                width: 460px;\r\n");
      out.write("                max-width: 95vw;\r\n");
      out.write("                padding: 45px 40px;\r\n");
      out.write("                position: relative;\r\n");
      out.write("                z-index: 1;\r\n");
      out.write("                animation: slideUp 0.5s ease-out;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            @keyframes slideUp {\r\n");
      out.write("                from {\r\n");
      out.write("                    opacity: 0;\r\n");
      out.write("                    transform: translateY(40px);\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                to {\r\n");
      out.write("                    opacity: 1;\r\n");
      out.write("                    transform: translateY(0);\r\n");
      out.write("                }\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            /* Shield icon */\r\n");
      out.write("            .shield-icon {\r\n");
      out.write("                width: 70px;\r\n");
      out.write("                height: 70px;\r\n");
      out.write("                background: linear-gradient(135deg, #ee4d2d, #ff7b54);\r\n");
      out.write("                border-radius: 50%;\r\n");
      out.write("                display: flex;\r\n");
      out.write("                align-items: center;\r\n");
      out.write("                justify-content: center;\r\n");
      out.write("                margin: 0 auto 20px;\r\n");
      out.write("                box-shadow: 0 8px 25px rgba(238, 77, 45, 0.3);\r\n");
      out.write("                animation: pulse 2s ease-in-out infinite;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            @keyframes pulse {\r\n");
      out.write("\r\n");
      out.write("                0%,\r\n");
      out.write("                100% {\r\n");
      out.write("                    box-shadow: 0 8px 25px rgba(238, 77, 45, 0.3);\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                50% {\r\n");
      out.write("                    box-shadow: 0 8px 40px rgba(238, 77, 45, 0.5);\r\n");
      out.write("                }\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .shield-icon i {\r\n");
      out.write("                color: white;\r\n");
      out.write("                font-size: 30px;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .otp-title {\r\n");
      out.write("                text-align: center;\r\n");
      out.write("                font-weight: 700;\r\n");
      out.write("                color: #222;\r\n");
      out.write("                font-size: 22px;\r\n");
      out.write("                margin-bottom: 8px;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .otp-subtitle {\r\n");
      out.write("                text-align: center;\r\n");
      out.write("                color: #888;\r\n");
      out.write("                font-size: 14px;\r\n");
      out.write("                margin-bottom: 30px;\r\n");
      out.write("                line-height: 1.5;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .otp-subtitle .email-highlight {\r\n");
      out.write("                color: #ee4d2d;\r\n");
      out.write("                font-weight: 600;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            /* OTP Input boxes */\r\n");
      out.write("            .otp-inputs {\r\n");
      out.write("                display: flex;\r\n");
      out.write("                gap: 10px;\r\n");
      out.write("                justify-content: center;\r\n");
      out.write("                margin-bottom: 25px;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .otp-inputs input {\r\n");
      out.write("                width: 52px;\r\n");
      out.write("                height: 60px;\r\n");
      out.write("                text-align: center;\r\n");
      out.write("                font-size: 24px;\r\n");
      out.write("                font-weight: 700;\r\n");
      out.write("                color: #333;\r\n");
      out.write("                border: 2px solid #e0e0e0;\r\n");
      out.write("                border-radius: 12px;\r\n");
      out.write("                outline: none;\r\n");
      out.write("                transition: all 0.3s ease;\r\n");
      out.write("                background: #fafafa;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .otp-inputs input:focus {\r\n");
      out.write("                border-color: #ee4d2d;\r\n");
      out.write("                background: #fff;\r\n");
      out.write("                box-shadow: 0 0 0 3px rgba(238, 77, 45, 0.15);\r\n");
      out.write("                transform: scale(1.05);\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .otp-inputs input.filled {\r\n");
      out.write("                border-color: #ee4d2d;\r\n");
      out.write("                background: #fff5f3;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .otp-inputs input.error-shake {\r\n");
      out.write("                animation: shake 0.4s ease;\r\n");
      out.write("                border-color: #dc3545;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            @keyframes shake {\r\n");
      out.write("\r\n");
      out.write("                0%,\r\n");
      out.write("                100% {\r\n");
      out.write("                    transform: translateX(0);\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                25% {\r\n");
      out.write("                    transform: translateX(-8px);\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                75% {\r\n");
      out.write("                    transform: translateX(8px);\r\n");
      out.write("                }\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            /* Timer */\r\n");
      out.write("            .timer-section {\r\n");
      out.write("                text-align: center;\r\n");
      out.write("                margin-bottom: 20px;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .timer-badge {\r\n");
      out.write("                display: inline-flex;\r\n");
      out.write("                align-items: center;\r\n");
      out.write("                gap: 6px;\r\n");
      out.write("                background: #f8f9fa;\r\n");
      out.write("                padding: 8px 16px;\r\n");
      out.write("                border-radius: 20px;\r\n");
      out.write("                font-size: 13px;\r\n");
      out.write("                color: #666;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .timer-badge .time {\r\n");
      out.write("                color: #ee4d2d;\r\n");
      out.write("                font-weight: 700;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .timer-badge.expired {\r\n");
      out.write("                background: #fff3cd;\r\n");
      out.write("                color: #856404;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            /* Submit button */\r\n");
      out.write("            .btn-verify {\r\n");
      out.write("                width: 100%;\r\n");
      out.write("                height: 48px;\r\n");
      out.write("                background: linear-gradient(135deg, #ee4d2d, #ff6b45);\r\n");
      out.write("                color: white;\r\n");
      out.write("                border: none;\r\n");
      out.write("                border-radius: 12px;\r\n");
      out.write("                font-size: 16px;\r\n");
      out.write("                font-weight: 600;\r\n");
      out.write("                cursor: pointer;\r\n");
      out.write("                transition: all 0.3s ease;\r\n");
      out.write("                display: flex;\r\n");
      out.write("                align-items: center;\r\n");
      out.write("                justify-content: center;\r\n");
      out.write("                gap: 8px;\r\n");
      out.write("                margin-bottom: 15px;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .btn-verify:hover {\r\n");
      out.write("                background: linear-gradient(135deg, #d73211, #ee4d2d);\r\n");
      out.write("                transform: translateY(-2px);\r\n");
      out.write("                box-shadow: 0 8px 25px rgba(238, 77, 45, 0.3);\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .btn-verify:disabled {\r\n");
      out.write("                opacity: 0.6;\r\n");
      out.write("                cursor: not-allowed;\r\n");
      out.write("                transform: none;\r\n");
      out.write("                box-shadow: none;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            /* Resend section */\r\n");
      out.write("            .resend-section {\r\n");
      out.write("                text-align: center;\r\n");
      out.write("                padding-top: 10px;\r\n");
      out.write("                border-top: 1px solid #f0f0f0;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .resend-text {\r\n");
      out.write("                color: #888;\r\n");
      out.write("                font-size: 13px;\r\n");
      out.write("                margin-bottom: 8px;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .btn-resend {\r\n");
      out.write("                background: none;\r\n");
      out.write("                border: 2px solid #ee4d2d;\r\n");
      out.write("                color: #ee4d2d;\r\n");
      out.write("                padding: 8px 24px;\r\n");
      out.write("                border-radius: 8px;\r\n");
      out.write("                font-size: 13px;\r\n");
      out.write("                font-weight: 600;\r\n");
      out.write("                cursor: pointer;\r\n");
      out.write("                transition: all 0.3s ease;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .btn-resend:hover:not(:disabled) {\r\n");
      out.write("                background: #ee4d2d;\r\n");
      out.write("                color: white;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .btn-resend:disabled {\r\n");
      out.write("                opacity: 0.4;\r\n");
      out.write("                cursor: not-allowed;\r\n");
      out.write("                border-color: #ccc;\r\n");
      out.write("                color: #ccc;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            /* Back link */\r\n");
      out.write("            .back-link {\r\n");
      out.write("                text-align: center;\r\n");
      out.write("                margin-top: 20px;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .back-link a {\r\n");
      out.write("                color: #888;\r\n");
      out.write("                font-size: 13px;\r\n");
      out.write("                text-decoration: none;\r\n");
      out.write("                transition: color 0.2s;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .back-link a:hover {\r\n");
      out.write("                color: #ee4d2d;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            /* Alert styles */\r\n");
      out.write("            .alert-custom {\r\n");
      out.write("                border-radius: 10px;\r\n");
      out.write("                padding: 12px 16px;\r\n");
      out.write("                font-size: 13px;\r\n");
      out.write("                margin-bottom: 20px;\r\n");
      out.write("                display: flex;\r\n");
      out.write("                align-items: center;\r\n");
      out.write("                gap: 8px;\r\n");
      out.write("                animation: slideDown 0.3s ease;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            @keyframes slideDown {\r\n");
      out.write("                from {\r\n");
      out.write("                    opacity: 0;\r\n");
      out.write("                    transform: translateY(-10px);\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                to {\r\n");
      out.write("                    opacity: 1;\r\n");
      out.write("                    transform: translateY(0);\r\n");
      out.write("                }\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .alert-error {\r\n");
      out.write("                background: #fff2f0;\r\n");
      out.write("                border: 1px solid #ffccc7;\r\n");
      out.write("                color: #cf1322;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .alert-success {\r\n");
      out.write("                background: #f6ffed;\r\n");
      out.write("                border: 1px solid #b7eb8f;\r\n");
      out.write("                color: #389e0d;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            /* Loading spinner */\r\n");
      out.write("            .spinner {\r\n");
      out.write("                display: none;\r\n");
      out.write("                width: 20px;\r\n");
      out.write("                height: 20px;\r\n");
      out.write("                border: 2px solid rgba(255, 255, 255, 0.3);\r\n");
      out.write("                border-top: 2px solid white;\r\n");
      out.write("                border-radius: 50%;\r\n");
      out.write("                animation: spin 0.8s linear infinite;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            @keyframes spin {\r\n");
      out.write("                to {\r\n");
      out.write("                    transform: rotate(360deg);\r\n");
      out.write("                }\r\n");
      out.write("            }\r\n");
      out.write("        </style>\r\n");
      out.write("    </head>\r\n");
      out.write("\r\n");
      out.write("    <body>\r\n");
      out.write("        <div class=\"bg-particles\"></div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"otp-card\">\r\n");
      out.write("            <!-- Shield Icon -->\r\n");
      out.write("            <div class=\"shield-icon\">\r\n");
      out.write("                <i class=\"fas fa-shield-halved\"></i>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <h2 class=\"otp-title\">Xác Thực Admin</h2>\r\n");
      out.write("            <p class=\"otp-subtitle\">\r\n");
      out.write("                Mã xác thực 6 số đã được gửi đến<br>\r\n");
      out.write("                <span class=\"email-highlight\">\r\n");
      out.write("                    ");
      out.print( session.getAttribute("adminMaskedEmail") !=null ? session.getAttribute("adminMaskedEmail")
                        : "***@***.com" );
      out.write("\r\n");
      out.write("                </span>\r\n");
      out.write("            </p>\r\n");
      out.write("\r\n");
      out.write("            <!-- Alert Messages -->\r\n");
      out.write("            ");
 String error=(String) request.getAttribute("error"); if (error !=null) { 
      out.write("\r\n");
      out.write("                <div class=\"alert-custom alert-error\">\r\n");
      out.write("                    <i class=\"fas fa-exclamation-circle\"></i>\r\n");
      out.write("                    ");
      out.print( error );
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("                ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("                    ");
 String success=(String) request.getAttribute("success"); if (success !=null) { 
      out.write("\r\n");
      out.write("                        <div class=\"alert-custom alert-success\">\r\n");
      out.write("                            <i class=\"fas fa-check-circle\"></i>\r\n");
      out.write("                            ");
      out.print( success );
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("                        ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("                            <!-- OTP Form -->\r\n");
      out.write("                            <form id=\"otpForm\" action=\"admin-verify-otp\" method=\"post\">\r\n");
      out.write("                                <div class=\"otp-inputs\">\r\n");
      out.write("                                    <input type=\"text\" name=\"otp1\" maxlength=\"1\" pattern=\"[0-9]\" inputmode=\"numeric\"\r\n");
      out.write("                                        autocomplete=\"off\" autofocus>\r\n");
      out.write("                                    <input type=\"text\" name=\"otp2\" maxlength=\"1\" pattern=\"[0-9]\" inputmode=\"numeric\"\r\n");
      out.write("                                        autocomplete=\"off\">\r\n");
      out.write("                                    <input type=\"text\" name=\"otp3\" maxlength=\"1\" pattern=\"[0-9]\" inputmode=\"numeric\"\r\n");
      out.write("                                        autocomplete=\"off\">\r\n");
      out.write("                                    <input type=\"text\" name=\"otp4\" maxlength=\"1\" pattern=\"[0-9]\" inputmode=\"numeric\"\r\n");
      out.write("                                        autocomplete=\"off\">\r\n");
      out.write("                                    <input type=\"text\" name=\"otp5\" maxlength=\"1\" pattern=\"[0-9]\" inputmode=\"numeric\"\r\n");
      out.write("                                        autocomplete=\"off\">\r\n");
      out.write("                                    <input type=\"text\" name=\"otp6\" maxlength=\"1\" pattern=\"[0-9]\" inputmode=\"numeric\"\r\n");
      out.write("                                        autocomplete=\"off\">\r\n");
      out.write("                                </div>\r\n");
      out.write("\r\n");
      out.write("                                <!-- Timer -->\r\n");
      out.write("                                <div class=\"timer-section\">\r\n");
      out.write("                                    <div class=\"timer-badge\" id=\"timerBadge\">\r\n");
      out.write("                                        <i class=\"fas fa-clock\"></i>\r\n");
      out.write("                                        Mã hết hạn sau: <span class=\"time\" id=\"countdown\">10:00</span>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("\r\n");
      out.write("                                <button type=\"submit\" class=\"btn-verify\" id=\"btnVerify\">\r\n");
      out.write("                                    <span id=\"btnText\">Xác Nhận</span>\r\n");
      out.write("                                    <div class=\"spinner\" id=\"spinner\"></div>\r\n");
      out.write("                                </button>\r\n");
      out.write("                            </form>\r\n");
      out.write("\r\n");
      out.write("                            <!-- Resend -->\r\n");
      out.write("                            <div class=\"resend-section\">\r\n");
      out.write("                                <p class=\"resend-text\">Không nhận được mã?</p>\r\n");
      out.write("                                <form action=\"admin-verify-otp\" method=\"post\" style=\"display: inline;\">\r\n");
      out.write("                                    <input type=\"hidden\" name=\"action\" value=\"resend\">\r\n");
      out.write("                                    <button type=\"submit\" class=\"btn-resend\" id=\"btnResend\">\r\n");
      out.write("                                        <i class=\"fas fa-redo-alt\"></i> Gửi lại mã\r\n");
      out.write("                                        <span id=\"resendTimer\"></span>\r\n");
      out.write("                                    </button>\r\n");
      out.write("                                </form>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <!-- Back to login -->\r\n");
      out.write("                            <div class=\"back-link\">\r\n");
      out.write("                                <a href=\"login\"><i class=\"fas fa-arrow-left\"></i> Quay lại trang đăng nhập</a>\r\n");
      out.write("                            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <script>\r\n");
      out.write("            // ════════════════════════════════════════════════\r\n");
      out.write("            // 1. AUTO-FOCUS & AUTO-JUMP BETWEEN OTP INPUTS\r\n");
      out.write("            // ════════════════════════════════════════════════\r\n");
      out.write("            const inputs = document.querySelectorAll('.otp-inputs input');\r\n");
      out.write("\r\n");
      out.write("            inputs.forEach((input, index) => {\r\n");
      out.write("                // Chỉ cho phép nhập số\r\n");
      out.write("                input.addEventListener('input', (e) => {\r\n");
      out.write("                    let val = e.target.value.replace(/[^0-9]/g, '');\r\n");
      out.write("                    e.target.value = val;\r\n");
      out.write("\r\n");
      out.write("                    if (val.length === 1) {\r\n");
      out.write("                        e.target.classList.add('filled');\r\n");
      out.write("                        // Nhảy sang ô tiếp theo\r\n");
      out.write("                        if (index < inputs.length - 1) {\r\n");
      out.write("                            inputs[index + 1].focus();\r\n");
      out.write("                        }\r\n");
      out.write("                    } else {\r\n");
      out.write("                        e.target.classList.remove('filled');\r\n");
      out.write("                    }\r\n");
      out.write("                });\r\n");
      out.write("\r\n");
      out.write("                // Backspace → quay lại ô trước\r\n");
      out.write("                input.addEventListener('keydown', (e) => {\r\n");
      out.write("                    if (e.key === 'Backspace' && !e.target.value && index > 0) {\r\n");
      out.write("                        inputs[index - 1].focus();\r\n");
      out.write("                        inputs[index - 1].value = '';\r\n");
      out.write("                        inputs[index - 1].classList.remove('filled');\r\n");
      out.write("                    }\r\n");
      out.write("                    // Enter → submit\r\n");
      out.write("                    if (e.key === 'Enter') {\r\n");
      out.write("                        e.preventDefault();\r\n");
      out.write("                        document.getElementById('otpForm').submit();\r\n");
      out.write("                    }\r\n");
      out.write("                });\r\n");
      out.write("\r\n");
      out.write("                // Paste support (dán mã 6 số)\r\n");
      out.write("                input.addEventListener('paste', (e) => {\r\n");
      out.write("                    e.preventDefault();\r\n");
      out.write("                    let pasteData = e.clipboardData.getData('text').replace(/[^0-9]/g, '');\r\n");
      out.write("                    if (pasteData.length >= 6) {\r\n");
      out.write("                        for (let i = 0; i < 6; i++) {\r\n");
      out.write("                            inputs[i].value = pasteData[i];\r\n");
      out.write("                            inputs[i].classList.add('filled');\r\n");
      out.write("                        }\r\n");
      out.write("                        inputs[5].focus();\r\n");
      out.write("                    }\r\n");
      out.write("                });\r\n");
      out.write("            });\r\n");
      out.write("\r\n");
      out.write("        // ════════════════════════════════════════════════\r\n");
      out.write("        // 2. COUNTDOWN TIMER (10 phút)\r\n");
      out.write("        // ════════════════════════════════════════════════\r\n");
      out.write("        ");

                Long otpExpiry = (Long) session.getAttribute("adminOtpExpiry");
            long remainMs = 0;
            if (otpExpiry != null) {
                remainMs = otpExpiry - System.currentTimeMillis();
                if (remainMs < 0) remainMs = 0;
            }
        
      out.write("\r\n");
      out.write("                let totalSeconds = Math.floor(");
      out.print( remainMs );
      out.write(" / 1000);\r\n");
      out.write("            const countdownEl = document.getElementById('countdown');\r\n");
      out.write("            const timerBadge = document.getElementById('timerBadge');\r\n");
      out.write("            const btnVerify = document.getElementById('btnVerify');\r\n");
      out.write("\r\n");
      out.write("            function updateCountdown() {\r\n");
      out.write("                if (totalSeconds <= 0) {\r\n");
      out.write("                    countdownEl.textContent = 'Đã hết hạn!';\r\n");
      out.write("                    timerBadge.classList.add('expired');\r\n");
      out.write("                    btnVerify.disabled = true;\r\n");
      out.write("                    return;\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                let mins = Math.floor(totalSeconds / 60);\r\n");
      out.write("                let secs = totalSeconds % 60;\r\n");
      out.write("                countdownEl.textContent = String(mins).padStart(2, '0') + ':' + String(secs).padStart(2, '0');\r\n");
      out.write("                totalSeconds--;\r\n");
      out.write("                setTimeout(updateCountdown, 1000);\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            updateCountdown();\r\n");
      out.write("\r\n");
      out.write("        // ════════════════════════════════════════════════\r\n");
      out.write("        // 3. RESEND COOLDOWN (60 giây)\r\n");
      out.write("        // ════════════════════════════════════════════════\r\n");
      out.write("        ");

                Long lastSent = (Long) session.getAttribute("adminOtpLastSent");
            long cooldownRemain = 0;
            if (lastSent != null) {
                cooldownRemain = 60 - ((System.currentTimeMillis() - lastSent) / 1000);
                if (cooldownRemain < 0) cooldownRemain = 0;
            }
        
      out.write("\r\n");
      out.write("                let resendCooldown = ");
      out.print( cooldownRemain );
      out.write(";\r\n");
      out.write("            const btnResend = document.getElementById('btnResend');\r\n");
      out.write("            const resendTimerEl = document.getElementById('resendTimer');\r\n");
      out.write("\r\n");
      out.write("            function updateResendCooldown() {\r\n");
      out.write("                if (resendCooldown <= 0) {\r\n");
      out.write("                    btnResend.disabled = false;\r\n");
      out.write("                    resendTimerEl.textContent = '';\r\n");
      out.write("                    return;\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                btnResend.disabled = true;\r\n");
      out.write("                resendTimerEl.textContent = ' (' + resendCooldown + 's)';\r\n");
      out.write("                resendCooldown--;\r\n");
      out.write("                setTimeout(updateResendCooldown, 1000);\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            updateResendCooldown();\r\n");
      out.write("\r\n");
      out.write("            // ════════════════════════════════════════════════\r\n");
      out.write("            // 4. SUBMIT LOADING STATE\r\n");
      out.write("            // ════════════════════════════════════════════════\r\n");
      out.write("            document.getElementById('otpForm').addEventListener('submit', function () {\r\n");
      out.write("                const btnText = document.getElementById('btnText');\r\n");
      out.write("                const spinner = document.getElementById('spinner');\r\n");
      out.write("                btnText.textContent = 'Đang xác thực...';\r\n");
      out.write("                spinner.style.display = 'block';\r\n");
      out.write("                btnVerify.disabled = true;\r\n");
      out.write("            });\r\n");
      out.write("        </script>\r\n");
      out.write("    </body>\r\n");
      out.write("\r\n");
      out.write("    </html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
