/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.19
 * Generated at: 2026-03-07 12:47:55 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    <!DOCTYPE html>\r\n");
      out.write("    <html lang=\"vi\">\r\n");
      out.write("\r\n");
      out.write("    <head>\r\n");
      out.write("        <meta charset=\"UTF-8\">\r\n");
      out.write("        <title>Đăng nhập | Shopee Việt Nam</title>\r\n");
      out.write("        <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css\">\r\n");
      out.write("\r\n");
      out.write("        <style>\r\n");
      out.write("            body {\r\n");
      out.write("                background: #f5f5f5;\r\n");
      out.write("                font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;\r\n");
      out.write("                overflow-x: hidden;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            /* HEADER */\r\n");
      out.write("            .login-header {\r\n");
      out.write("                background: #fff;\r\n");
      out.write("                padding: 20px 0;\r\n");
      out.write("                box-shadow: 0 4px 10px rgba(0, 0, 0, .05);\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .shopee-logo {\r\n");
      out.write("                color: #ee4d2d;\r\n");
      out.write("                font-size: 30px;\r\n");
      out.write("                text-decoration: none;\r\n");
      out.write("                display: flex;\r\n");
      out.write("                align-items: center;\r\n");
      out.write("                gap: 10px;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .page-title {\r\n");
      out.write("                color: #222;\r\n");
      out.write("                font-size: 22px;\r\n");
      out.write("                margin-top: 5px;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            /* BODY */\r\n");
      out.write("            .login-body {\r\n");
      out.write("                background-color: #ee4d2d;\r\n");
      out.write("                min-height: 550px;\r\n");
      out.write("                display: flex;\r\n");
      out.write("                align-items: center;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .banner-img {\r\n");
      out.write("                width: 100%;\r\n");
      out.write("                max-width: 550px;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            /* CARD LOGIN */\r\n");
      out.write("            .login-card {\r\n");
      out.write("                background: #fff;\r\n");
      out.write("                width: 400px;\r\n");
      out.write("                padding: 30px;\r\n");
      out.write("                border-radius: 4px;\r\n");
      out.write("                box-shadow: 0 3px 10px 0 rgba(0, 0, 0, .14);\r\n");
      out.write("                margin-left: auto;\r\n");
      out.write("                position: relative;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .login-title {\r\n");
      out.write("                font-size: 20px;\r\n");
      out.write("                color: #222;\r\n");
      out.write("                margin-bottom: 25px;\r\n");
      out.write("                font-weight: 500;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .form-control {\r\n");
      out.write("                height: 42px;\r\n");
      out.write("                font-size: 14px;\r\n");
      out.write("                border-radius: 2px;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .form-control:focus {\r\n");
      out.write("                box-shadow: none;\r\n");
      out.write("                border-color: #777;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .btn-login {\r\n");
      out.write("                background: #ee4d2d;\r\n");
      out.write("                color: #fff;\r\n");
      out.write("                width: 100%;\r\n");
      out.write("                height: 42px;\r\n");
      out.write("                border: none;\r\n");
      out.write("                border-radius: 2px;\r\n");
      out.write("                font-size: 14px;\r\n");
      out.write("                text-transform: uppercase;\r\n");
      out.write("                margin-top: 15px;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .btn-login:hover {\r\n");
      out.write("                background: #d73211;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .separator {\r\n");
      out.write("                display: flex;\r\n");
      out.write("                align-items: center;\r\n");
      out.write("                margin: 20px 0;\r\n");
      out.write("                color: #dbdbdb;\r\n");
      out.write("                font-size: 12px;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .separator::before,\r\n");
      out.write("            .separator::after {\r\n");
      out.write("                content: \"\";\r\n");
      out.write("                flex: 1;\r\n");
      out.write("                height: 1px;\r\n");
      out.write("                background: #dbdbdb;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .separator span {\r\n");
      out.write("                padding: 0 10px;\r\n");
      out.write("                color: #ccc;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .social-btns {\r\n");
      out.write("                display: flex;\r\n");
      out.write("                gap: 10px;\r\n");
      out.write("                justify-content: space-between;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .btn-social {\r\n");
      out.write("                flex: 1;\r\n");
      out.write("                height: 40px;\r\n");
      out.write("                border: 1px solid rgba(0, 0, 0, .26);\r\n");
      out.write("                background: #fff;\r\n");
      out.write("                display: flex;\r\n");
      out.write("                align-items: center;\r\n");
      out.write("                justify-content: center;\r\n");
      out.write("                gap: 8px;\r\n");
      out.write("                font-size: 14px;\r\n");
      out.write("                text-decoration: none;\r\n");
      out.write("                color: #000;\r\n");
      out.write("                border-radius: 2px;\r\n");
      out.write("                cursor: pointer;\r\n");
      out.write("                transition: all .2s;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .btn-social:hover {\r\n");
      out.write("                background: #f5f5f5;\r\n");
      out.write("                border-color: rgba(0,0,0,.4);\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .btn-social.fb:hover { border-color: #1877f2; color: #1877f2; }\r\n");
      out.write("            .btn-social.gg:hover { border-color: #ea4335; color: #ea4335; }\r\n");
      out.write("\r\n");
      out.write("            /* QR CODE CORNER (Giả lập giống Shopee) */\r\n");
      out.write("            .qr-corner {\r\n");
      out.write("                position: absolute;\r\n");
      out.write("                top: 0;\r\n");
      out.write("                right: 0;\r\n");
      out.write("                cursor: pointer;\r\n");
      out.write("                width: 70px;\r\n");
      out.write("                height: 70px;\r\n");
      out.write("                background: url('https://deo.shopeemobile.com/shopee/shopee-pcmall-live-sg/assets/32a93b426038421c.png') no-repeat;\r\n");
      out.write("                background-size: cover;\r\n");
      out.write("                clip-path: polygon(0 0, 100% 0, 100% 100%);\r\n");
      out.write("                z-index: 10;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .qr-tooltip {\r\n");
      out.write("                position: absolute;\r\n");
      out.write("                top: 15px;\r\n");
      out.write("                right: 80px;\r\n");
      out.write("                background: rgba(255, 239, 235, 0.9);\r\n");
      out.write("                border: 2px solid #ffbfb5;\r\n");
      out.write("                color: #ee4d2d;\r\n");
      out.write("                padding: 10px 15px;\r\n");
      out.write("                font-size: 13px;\r\n");
      out.write("                font-weight: bold;\r\n");
      out.write("                border-radius: 2px;\r\n");
      out.write("                width: 180px;\r\n");
      out.write("                text-align: center;\r\n");
      out.write("                z-index: 10;\r\n");
      out.write("                cursor: pointer;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .qr-tooltip::after {\r\n");
      out.write("                content: '';\r\n");
      out.write("                position: absolute;\r\n");
      out.write("                top: 50%;\r\n");
      out.write("                right: -6px;\r\n");
      out.write("                transform: translateY(-50%);\r\n");
      out.write("                border-width: 6px;\r\n");
      out.write("                border-style: solid;\r\n");
      out.write("                border-color: transparent transparent transparent #ffbfb5;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            /* Màn hình QR */\r\n");
      out.write("            #qr-view {\r\n");
      out.write("                display: none;\r\n");
      out.write("                text-align: center;\r\n");
      out.write("                padding-top: 10px;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .qr-container {\r\n");
      out.write("                width: 200px;\r\n");
      out.write("                height: 200px;\r\n");
      out.write("                margin: 0 auto 15px;\r\n");
      out.write("                border: 1px solid #eee;\r\n");
      out.write("                padding: 10px;\r\n");
      out.write("                display: flex;\r\n");
      out.write("                align-items: center;\r\n");
      out.write("                justify-content: center;\r\n");
      out.write("                position: relative;\r\n");
      out.write("                border-radius: 4px;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .qr-container canvas { max-width: 100%; max-height: 100%; }\r\n");
      out.write("\r\n");
      out.write("            .qr-status {\r\n");
      out.write("                font-size: 13px;\r\n");
      out.write("                margin: 10px 0;\r\n");
      out.write("                padding: 8px 12px;\r\n");
      out.write("                border-radius: 4px;\r\n");
      out.write("            }\r\n");
      out.write("            .qr-status.pending { background: #fff3cd; color: #856404; }\r\n");
      out.write("            .qr-status.success { background: #d4edda; color: #155724; }\r\n");
      out.write("            .qr-status.error { background: #f8d7da; color: #721c24; }\r\n");
      out.write("\r\n");
      out.write("            .btn-confirm-qr {\r\n");
      out.write("                background: #ee4d2d;\r\n");
      out.write("                color: #fff;\r\n");
      out.write("                border: none;\r\n");
      out.write("                padding: 10px 24px;\r\n");
      out.write("                border-radius: 4px;\r\n");
      out.write("                font-size: 14px;\r\n");
      out.write("                cursor: pointer;\r\n");
      out.write("                margin-top: 10px;\r\n");
      out.write("                transition: background .2s;\r\n");
      out.write("            }\r\n");
      out.write("            .btn-confirm-qr:hover { background: #d73211; }\r\n");
      out.write("\r\n");
      out.write("            .btn-refresh-qr {\r\n");
      out.write("                background: #f5f5f5;\r\n");
      out.write("                color: #333;\r\n");
      out.write("                border: 1px solid #ddd;\r\n");
      out.write("                padding: 8px 16px;\r\n");
      out.write("                border-radius: 4px;\r\n");
      out.write("                font-size: 13px;\r\n");
      out.write("                cursor: pointer;\r\n");
      out.write("                margin-top: 8px;\r\n");
      out.write("                transition: all .2s;\r\n");
      out.write("            }\r\n");
      out.write("            .btn-refresh-qr:hover { background: #eee; }\r\n");
      out.write("\r\n");
      out.write("            /* Loading spinner cho QR */\r\n");
      out.write("            .qr-loading {\r\n");
      out.write("                width: 40px;\r\n");
      out.write("                height: 40px;\r\n");
      out.write("                border: 3px solid #f0f0f0;\r\n");
      out.write("                border-top-color: #ee4d2d;\r\n");
      out.write("                border-radius: 50%;\r\n");
      out.write("                animation: spin .8s linear infinite;\r\n");
      out.write("            }\r\n");
      out.write("            @keyframes spin { to { transform: rotate(360deg); }}\r\n");
      out.write("\r\n");
      out.write("            /* Pulse animation */\r\n");
      out.write("            @keyframes pulse {\r\n");
      out.write("                0% { transform: scale(1); }\r\n");
      out.write("                50% { transform: scale(1.02); }\r\n");
      out.write("                100% { transform: scale(1); }\r\n");
      out.write("            }\r\n");
      out.write("            .qr-scanning .qr-container {\r\n");
      out.write("                border-color: #ee4d2d;\r\n");
      out.write("                animation: pulse 2s ease-in-out infinite;\r\n");
      out.write("            }\r\n");
      out.write("        </style>\r\n");
      out.write("    </head>\r\n");
      out.write("\r\n");
      out.write("    <body>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"login-header\">\r\n");
      out.write("            <div class=\"container d-flex align-items-center justify-content-between\">\r\n");
      out.write("                <a href=\"home\" class=\"shopee-logo\">\r\n");
      out.write("                    <i class=\"fas fa-shopping-bag\"></i>\r\n");
      out.write("                    <span class=\"fw-bold\">Shopee</span>\r\n");
      out.write("                    <span class=\"page-title\">Đăng nhập</span>\r\n");
      out.write("                </a>\r\n");
      out.write("                <a href=\"#\" class=\"text-danger text-decoration-none small\"\r\n");
      out.write("                    onclick=\"alert('Liên hệ tổng đài 19001221')\">Bạn cần giúp đỡ?</a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"login-body\">\r\n");
      out.write("            <div class=\"container d-flex justify-content-between align-items-center\">\r\n");
      out.write("\r\n");
      out.write("                <div class=\"d-none d-lg-block text-center text-white\">\r\n");
      out.write("                    <div style=\"max-width:400px; margin:0 auto;\">\r\n");
      out.write("                        <i class=\"fas fa-shopping-bag\" style=\"font-size:120px; opacity:0.9; margin-bottom:20px; display:block;\"></i>\r\n");
      out.write("                        <div style=\"display:inline-flex; align-items:center; gap:8px; background:rgba(255,255,255,0.15); padding:8px 20px; border-radius:4px; margin-bottom:15px;\">\r\n");
      out.write("                            <i class=\"fas fa-store\" style=\"font-size:22px;\"></i>\r\n");
      out.write("                            <span style=\"font-size:26px; font-weight:700; letter-spacing:1px;\">Shopee Mall</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"mt-3 fw-bold fs-5\">Yêu thích nhất Đông Nam Á</div>\r\n");
      out.write("                        <div class=\"mt-2\" style=\"font-size:14px; opacity:0.85;\">Mua sắm online - giá tốt mỗi ngày</div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"login-card\">\r\n");
      out.write("                    <div class=\"qr-corner\" onclick=\"toggleQR()\"></div>\r\n");
      out.write("                    <div class=\"qr-tooltip\" id=\"qr-tooltip\" onclick=\"toggleQR()\">Đăng nhập với mã QR</div>\r\n");
      out.write("\r\n");
      out.write("                    <!-- ========== FORM VIEW ========== -->\r\n");
      out.write("                    <div id=\"form-view\">\r\n");
      out.write("                        <div class=\"login-title\">Đăng nhập</div>\r\n");
      out.write("\r\n");
      out.write("                        ");
 String err=(String) request.getAttribute("error"); if (err !=null) {
      out.write("\r\n");
      out.write("                            <div class=\"alert alert-danger py-2 small\"><i class=\"fas fa-exclamation-circle\"></i>\r\n");
      out.write("                                ");
      out.print( err);
      out.write("\r\n");
      out.write("                            </div>\r\n");
      out.write("                        ");
 }
      out.write("\r\n");
      out.write("\r\n");
      out.write("                        ");
 String mess=(String) request.getAttribute("mess"); if (mess !=null) {
      out.write("\r\n");
      out.write("                            <div class=\"alert alert-success py-2 small\"><i class=\"fas fa-check-circle\"></i>\r\n");
      out.write("                                ");
      out.print( mess);
      out.write("\r\n");
      out.write("                            </div>\r\n");
      out.write("                        ");
 }
      out.write("\r\n");
      out.write("\r\n");
      out.write("                        <form action=\"login\" method=\"post\">\r\n");
      out.write("                            <div class=\"mb-3\">\r\n");
      out.write("                                <input type=\"text\" name=\"user\" class=\"form-control\"\r\n");
      out.write("                                    placeholder=\"Email / Số điện thoại / Tên đăng nhập\" required>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"mb-3\">\r\n");
      out.write("                                <input type=\"password\" name=\"pass\" class=\"form-control\"\r\n");
      out.write("                                    placeholder=\"Mật khẩu\" required>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <button type=\"submit\" class=\"btn-login\">Đăng nhập</button>\r\n");
      out.write("                        </form>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"d-flex justify-content-between mt-3 small\">\r\n");
      out.write("                            <a href=\"javascript:void(0)\" class=\"text-primary text-decoration-none\"\r\n");
      out.write("                                onclick=\"alert('Chức năng Quên mật khẩu đang bảo trì!')\">Quên mật\r\n");
      out.write("                                khẩu</a>\r\n");
      out.write("                            <a href=\"javascript:void(0)\" class=\"text-secondary text-decoration-none\"\r\n");
      out.write("                                onclick=\"alert('Hệ thống SMS đang hết tiền!')\">Đăng nhập với SMS</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"separator\"><span>HOẶC</span></div>\r\n");
      out.write("\r\n");
      out.write("                        <!-- ===== SOCIAL LOGIN BUTTONS ===== -->\r\n");
      out.write("                        <div class=\"social-btns\">\r\n");
      out.write("                            <a href=\"facebook-login\" class=\"btn-social fb\">\r\n");
      out.write("                                <i class=\"fab fa-facebook text-primary\"></i> Facebook\r\n");
      out.write("                            </a>\r\n");
      out.write("                            <a href=\"google-login\" class=\"btn-social gg\">\r\n");
      out.write("                                <i class=\"fab fa-google text-danger\"></i> Google\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"text-center mt-4 small\">\r\n");
      out.write("                            <span class=\"text-muted\">Bạn mới biết đến Shopee?</span>\r\n");
      out.write("                            <a href=\"register\" class=\"text-danger fw-bold text-decoration-none\">Đăng\r\n");
      out.write("                                ký</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <!-- ========== QR VIEW ========== -->\r\n");
      out.write("                    <div id=\"qr-view\">\r\n");
      out.write("                        <div class=\"login-title\">Đăng nhập với mã QR</div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"qr-container\" id=\"qrContainer\">\r\n");
      out.write("                            <div class=\"qr-loading\" id=\"qrLoading\"></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"qr-status pending\" id=\"qrStatus\">\r\n");
      out.write("                            <i class=\"fas fa-spinner fa-spin\"></i> Đang tạo mã QR...\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <p class=\"small text-muted mb-1\">Quét mã QR bằng ứng dụng Shopee</p>\r\n");
      out.write("\r\n");
      out.write("                        <button class=\"btn-confirm-qr\" id=\"btnConfirmQr\" style=\"display:none\"\r\n");
      out.write("                                onclick=\"confirmQrScan()\">\r\n");
      out.write("                            <i class=\"fas fa-mobile-alt\"></i> Giả lập quét QR (Demo)\r\n");
      out.write("                        </button>\r\n");
      out.write("\r\n");
      out.write("                        <button class=\"btn-refresh-qr\" id=\"btnRefreshQr\" style=\"display:none\"\r\n");
      out.write("                                onclick=\"generateQrCode()\">\r\n");
      out.write("                            <i class=\"fas fa-redo\"></i> Tạo mã QR mới\r\n");
      out.write("                        </button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"container py-5 text-center small text-secondary\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-12 mb-3\">\r\n");
      out.write("                    <span class=\"mx-3\">CHÍNH SÁCH BẢO MẬT</span>\r\n");
      out.write("                    <span class=\"mx-3\">QUY CHẾ HOẠT ĐỘNG</span>\r\n");
      out.write("                    <span class=\"mx-3\">CHÍNH SÁCH VẬN CHUYỂN</span>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-12\">\r\n");
      out.write("                    <img src=\"https://down-vn.img.susercontent.com/file/d4bbea4570b93bfd5fc652ca82a262a8\" width=\"100\">\r\n");
      out.write("                    <p class=\"mt-2\">© 2026 Shopee. Tất cả các quyền được bảo lưu.</p>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- QR Code Generator Library -->\r\n");
      out.write("        <script src=\"https://cdn.jsdelivr.net/npm/qrcodejs@1.0.0/qrcode.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("        <script>\r\n");
      out.write("            // ==========================================\r\n");
      out.write("            // 1. TOGGLE QR / FORM VIEW\r\n");
      out.write("            // ==========================================\r\n");
      out.write("            let isQR = false;\r\n");
      out.write("            let qrToken = null;\r\n");
      out.write("            let pollingInterval = null;\r\n");
      out.write("\r\n");
      out.write("            function toggleQR() {\r\n");
      out.write("                isQR = !isQR;\r\n");
      out.write("                let formView = document.getElementById('form-view');\r\n");
      out.write("                let qrView = document.getElementById('qr-view');\r\n");
      out.write("                let tooltip = document.getElementById('qr-tooltip');\r\n");
      out.write("\r\n");
      out.write("                if (isQR) {\r\n");
      out.write("                    formView.style.display = 'none';\r\n");
      out.write("                    qrView.style.display = 'block';\r\n");
      out.write("                    tooltip.innerHTML = 'Đăng nhập với tài khoản';\r\n");
      out.write("                    // Tạo QR code khi chuyển sang qr-view\r\n");
      out.write("                    generateQrCode();\r\n");
      out.write("                } else {\r\n");
      out.write("                    formView.style.display = 'block';\r\n");
      out.write("                    qrView.style.display = 'none';\r\n");
      out.write("                    tooltip.innerHTML = 'Đăng nhập với mã QR';\r\n");
      out.write("                    // Dừng polling khi quay lại form\r\n");
      out.write("                    stopPolling();\r\n");
      out.write("                }\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            // ==========================================\r\n");
      out.write("            // 2. GOOGLE: Direct redirect (href=\"google-login\")\r\n");
      out.write("            // 3. FACEBOOK: Direct redirect (href=\"facebook-login\")\r\n");
      out.write("            // ==========================================\r\n");
      out.write("\r\n");
      out.write("            // ==========================================\r\n");
      out.write("            // 3. QR CODE LOGIN\r\n");
      out.write("            // ==========================================\r\n");
      out.write("            function generateQrCode() {\r\n");
      out.write("                stopPolling();\r\n");
      out.write("\r\n");
      out.write("                let container = document.getElementById('qrContainer');\r\n");
      out.write("                let status = document.getElementById('qrStatus');\r\n");
      out.write("                let btnConfirm = document.getElementById('btnConfirmQr');\r\n");
      out.write("                let btnRefresh = document.getElementById('btnRefreshQr');\r\n");
      out.write("\r\n");
      out.write("                // Reset UI\r\n");
      out.write("                container.innerHTML = '<div class=\"qr-loading\"></div>';\r\n");
      out.write("                status.className = 'qr-status pending';\r\n");
      out.write("                status.innerHTML = '<i class=\"fas fa-spinner fa-spin\"></i> Đang tạo mã QR...';\r\n");
      out.write("                btnConfirm.style.display = 'none';\r\n");
      out.write("                btnRefresh.style.display = 'none';\r\n");
      out.write("\r\n");
      out.write("                // Gọi API tạo token\r\n");
      out.write("                fetch('qr-login?action=generate')\r\n");
      out.write("                    .then(r => r.json())\r\n");
      out.write("                    .then(data => {\r\n");
      out.write("                        if (data.token) {\r\n");
      out.write("                            qrToken = data.token;\r\n");
      out.write("                            container.innerHTML = '';\r\n");
      out.write("\r\n");
      out.write("                            // Tạo QR Code bằng thư viện qrcodejs\r\n");
      out.write("                            new QRCode(container, {\r\n");
      out.write("                                text: 'shopee://qr-login?token=' + qrToken,\r\n");
      out.write("                                width: 170,\r\n");
      out.write("                                height: 170,\r\n");
      out.write("                                colorDark: '#000000',\r\n");
      out.write("                                colorLight: '#ffffff',\r\n");
      out.write("                                correctLevel: QRCode.CorrectLevel.H\r\n");
      out.write("                            });\r\n");
      out.write("\r\n");
      out.write("                            status.className = 'qr-status pending';\r\n");
      out.write("                            status.innerHTML = '<i class=\"fas fa-qrcode\"></i> Quét mã để đăng nhập';\r\n");
      out.write("                            btnConfirm.style.display = 'inline-block';\r\n");
      out.write("                            btnRefresh.style.display = 'none';\r\n");
      out.write("\r\n");
      out.write("                            // Bắt đầu polling\r\n");
      out.write("                            startPolling();\r\n");
      out.write("                        }\r\n");
      out.write("                    })\r\n");
      out.write("                    .catch(err => {\r\n");
      out.write("                        container.innerHTML = '<i class=\"fas fa-exclamation-triangle text-danger\" style=\"font-size:40px\"></i>';\r\n");
      out.write("                        status.className = 'qr-status error';\r\n");
      out.write("                        status.innerHTML = '<i class=\"fas fa-times-circle\"></i> Lỗi tạo mã QR!';\r\n");
      out.write("                        btnRefresh.style.display = 'inline-block';\r\n");
      out.write("                    });\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            function startPolling() {\r\n");
      out.write("                pollingInterval = setInterval(() => {\r\n");
      out.write("                    if (!qrToken) return;\r\n");
      out.write("\r\n");
      out.write("                    fetch('qr-login?action=check&token=' + qrToken)\r\n");
      out.write("                        .then(r => r.json())\r\n");
      out.write("                        .then(data => {\r\n");
      out.write("                            let status = document.getElementById('qrStatus');\r\n");
      out.write("\r\n");
      out.write("                            if (data.status === 'CONFIRMED') {\r\n");
      out.write("                                stopPolling();\r\n");
      out.write("                                status.className = 'qr-status success';\r\n");
      out.write("                                status.innerHTML = '<i class=\"fas fa-check-circle\"></i> Đăng nhập thành công! Đang chuyển trang...';\r\n");
      out.write("                                document.getElementById('btnConfirmQr').style.display = 'none';\r\n");
      out.write("\r\n");
      out.write("                                // Chuyển trang\r\n");
      out.write("                                setTimeout(() => {\r\n");
      out.write("                                    window.location.href = data.redirect || 'home';\r\n");
      out.write("                                }, 1000);\r\n");
      out.write("                            } else if (data.status === 'EXPIRED') {\r\n");
      out.write("                                stopPolling();\r\n");
      out.write("                                status.className = 'qr-status error';\r\n");
      out.write("                                status.innerHTML = '<i class=\"fas fa-clock\"></i> Mã QR đã hết hạn!';\r\n");
      out.write("                                document.getElementById('btnConfirmQr').style.display = 'none';\r\n");
      out.write("                                document.getElementById('btnRefreshQr').style.display = 'inline-block';\r\n");
      out.write("                            }\r\n");
      out.write("                        });\r\n");
      out.write("                }, 2000); // Polling mỗi 2 giây\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            function stopPolling() {\r\n");
      out.write("                if (pollingInterval) {\r\n");
      out.write("                    clearInterval(pollingInterval);\r\n");
      out.write("                    pollingInterval = null;\r\n");
      out.write("                }\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            function confirmQrScan() {\r\n");
      out.write("                if (!qrToken) return;\r\n");
      out.write("\r\n");
      out.write("                let btn = document.getElementById('btnConfirmQr');\r\n");
      out.write("                btn.disabled = true;\r\n");
      out.write("                btn.innerHTML = '<i class=\"fas fa-spinner fa-spin\"></i> Đang xác nhận...';\r\n");
      out.write("\r\n");
      out.write("                // Giả lập quét QR\r\n");
      out.write("                fetch('qr-login?action=confirm&token=' + qrToken, {\r\n");
      out.write("                    method: 'POST',\r\n");
      out.write("                    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },\r\n");
      out.write("                    body: 'token=' + qrToken + '&action=confirm'\r\n");
      out.write("                })\r\n");
      out.write("                .then(r => r.json())\r\n");
      out.write("                .then(data => {\r\n");
      out.write("                    if (data.success) {\r\n");
      out.write("                        let status = document.getElementById('qrStatus');\r\n");
      out.write("                        status.className = 'qr-status success';\r\n");
      out.write("                        status.innerHTML = '<i class=\"fas fa-mobile-alt\"></i> Quét QR thành công! Đang xác nhận...';\r\n");
      out.write("                    } else {\r\n");
      out.write("                        btn.disabled = false;\r\n");
      out.write("                        btn.innerHTML = '<i class=\"fas fa-mobile-alt\"></i> Giả lập quét QR (Demo)';\r\n");
      out.write("                        alert('Lỗi xác nhận: ' + (data.error || 'Unknown'));\r\n");
      out.write("                    }\r\n");
      out.write("                });\r\n");
      out.write("            }\r\n");
      out.write("        </script>\r\n");
      out.write("    </body>\r\n");
      out.write("\r\n");
      out.write("    </html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
