/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.19
 * Generated at: 2026-03-01 14:07:18 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class register_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"vi\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <title>Đăng ký ngay | Shopee Việt Nam</title>\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css\">\r\n");
      out.write("    <style>\r\n");
      out.write("        body { background-color: rgb(238, 77, 45); font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; }\r\n");
      out.write("        .shopee-header { background: white; padding: 24px 0; margin-bottom: 0; box-shadow: 0 6px 6px -5px rgba(0,0,0,0.05); }\r\n");
      out.write("        .header-container { width: 1040px; margin: 0 auto; display: flex; align-items: center; justify-content: space-between; }\r\n");
      out.write("        .shopee-logo { color: #ee4d2d; font-size: 34px; font-weight: 500; text-decoration: none; display: flex; align-items: flex-end; gap: 15px; }\r\n");
      out.write("        .shopee-logo i { font-size: 40px; }\r\n");
      out.write("        .page-title { color: #222; font-size: 24px; margin-bottom: 2px; }\r\n");
      out.write("        \r\n");
      out.write("        .register-body { background: #ee4d2d; min-height: 600px; display: flex; align-items: center; justify-content: center; }\r\n");
      out.write("        .register-wrapper { width: 1040px; display: flex; align-items: center; justify-content: space-between; }\r\n");
      out.write("        \r\n");
      out.write("        .branding-image { flex: 1; text-align: center; color: white; display: flex; flex-direction: column; align-items: center; }\r\n");
      out.write("        .branding-image i { font-size: 180px; opacity: 0.9; margin-bottom: 20px;}\r\n");
      out.write("        .branding-text { font-size: 26px; font-weight: 500; }\r\n");
      out.write("\r\n");
      out.write("        .register-card { background: white; width: 400px; padding: 30px; border-radius: 4px; box-shadow: 0 3px 10px rgba(0,0,0,0.14); }\r\n");
      out.write("        .form-control { border-radius: 2px; padding: 12px; font-size: 14px; margin-bottom: 15px; border: 1px solid #dbdbdb; }\r\n");
      out.write("        .btn-shopee { background-color: #ee4d2d; color: white; width: 100%; border: none; padding: 12px; text-transform: uppercase; font-size: 14px; border-radius: 2px; box-shadow: 0 1px 1px rgba(0,0,0,.09); }\r\n");
      out.write("        .btn-shopee:hover { background-color: #d73211; color: white; }\r\n");
      out.write("\r\n");
      out.write("        .footer { background: #f5f5f5; padding: 40px 0; text-align: center; color: #757575; font-size: 12px; }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"shopee-header\">\r\n");
      out.write("        <div class=\"header-container\">\r\n");
      out.write("            <a href=\"home\" class=\"shopee-logo\">\r\n");
      out.write("                <i class=\"fas fa-shopping-bag\"></i>\r\n");
      out.write("                <span class=\"page-title\">Đăng ký</span>\r\n");
      out.write("            </a>\r\n");
      out.write("            <a href=\"#\" class=\"text-danger text-decoration-none small\">Bạn cần giúp đỡ?</a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"register-body\">\r\n");
      out.write("        <div class=\"register-wrapper\">\r\n");
      out.write("            <div class=\"branding-image d-none d-lg-flex\">\r\n");
      out.write("                <i class=\"fas fa-shopping-basket\"></i>\r\n");
      out.write("                <div class=\"branding-text\">Nền tảng thương mại điện tử<br>yêu thích ở Đông Nam Á</div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"register-card\">\r\n");
      out.write("                <div style=\"font-size: 20px; margin-bottom: 25px;\">Đăng ký</div>\r\n");
      out.write("                \r\n");
      out.write("                ");
 if(request.getAttribute("mess") != null) { 
      out.write("\r\n");
      out.write("                    <div class=\"alert alert-danger py-2 small text-center\">");
      out.print( request.getAttribute("mess") );
      out.write("</div>\r\n");
      out.write("                ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("                <form action=\"register\" method=\"post\">\r\n");
      out.write("                    <input type=\"text\" name=\"email\" class=\"form-control\" required placeholder=\"Email (Tên đăng nhập)\">\r\n");
      out.write("                    <input type=\"text\" name=\"fullname\" class=\"form-control\" required placeholder=\"Họ và Tên\">\r\n");
      out.write("                    <input type=\"text\" name=\"phone\" class=\"form-control\" required placeholder=\"Số điện thoại\">\r\n");
      out.write("                    <input type=\"password\" name=\"password\" class=\"form-control\" required placeholder=\"Mật khẩu\">\r\n");
      out.write("                    <input type=\"password\" name=\"re-password\" class=\"form-control\" required placeholder=\"Nhập lại mật khẩu\">\r\n");
      out.write("                    \r\n");
      out.write("                    <button type=\"submit\" class=\"btn btn-shopee mb-3\">TIẾP THEO</button>\r\n");
      out.write("                    \r\n");
      out.write("                    <div class=\"text-center small text-muted\">\r\n");
      out.write("                        Bằng việc đăng kí, bạn đồng ý với <a href=\"#\" class=\"text-danger text-decoration-none\">Điều khoản Shopee</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                    <div class=\"text-center small mt-4\">\r\n");
      out.write("                        Bạn đã có tài khoản? <a href=\"login\" class=\"text-danger fw-bold text-decoration-none\">Đăng nhập</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </form>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"footer\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div style=\"margin-bottom: 20px;\">\r\n");
      out.write("                <span style=\"margin: 0 10px;\">CHÍNH SÁCH BẢO MẬT</span> |\r\n");
      out.write("                <span style=\"margin: 0 10px;\">QUY CHẾ HOẠT ĐỘNG</span> |\r\n");
      out.write("                <span style=\"margin: 0 10px;\">VẬN CHUYỂN</span>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div>© 2026 Shopee. Tất cả các quyền được bảo lưu.</div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
