/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.19
 * Generated at: 2026-03-04 08:06:13 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import model.User;

public final class seller_005fonboarding_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(1);
    _jspx_imports_classes.add("model.User");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"vi\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Đăng ký trở thành Người bán — MarketplaceX</title>\r\n");
      out.write("    <meta name=\"description\" content=\"Đăng ký bán hàng trên MarketplaceX — Nền tảng thương mại điện tử hàng đầu Việt Nam\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.1/normalize.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/seller_onboarding.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"so-page\">\r\n");
      out.write("\r\n");
      out.write("    <!-- ==================== HEADER ==================== -->\r\n");
      out.write("    <header class=\"so-header\">\r\n");
      out.write("        <div class=\"so-header__left\">\r\n");
      out.write("            <a href=\"home\" class=\"so-header__logo\">\r\n");
      out.write("                <i class=\"fa-solid fa-bag-shopping\"></i> Shopee\r\n");
      out.write("            </a>\r\n");
      out.write("            <span class=\"so-header__title\">Đăng ký trở thành Người bán Shopee</span>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"so-header__right\">\r\n");
      out.write("            <button class=\"so-theme-toggle\" id=\"themeToggleBtn\" title=\"Chuyển giao diện\" aria-label=\"Chuyển đổi giao diện sáng/tối\">\r\n");
      out.write("                <i class=\"fas fa-moon\"></i>\r\n");
      out.write("            </button>\r\n");
      out.write("            ");
 User acc = (User) session.getAttribute("account");
               if (acc != null) { 
      out.write("\r\n");
      out.write("                <span style=\"color:#fff;font-size:14px;font-weight:500;\">\r\n");
      out.write("                    <i class=\"fas fa-user-circle\"></i> ");
      out.print( acc.getFullName() );
      out.write("\r\n");
      out.write("                </span>\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("    </header>\r\n");
      out.write("\r\n");
      out.write("    <!-- ==================== MAIN CONTAINER ==================== -->\r\n");
      out.write("    <main class=\"so-container\">\r\n");
      out.write("\r\n");
      out.write("        <!-- ==================== STEPPER ==================== -->\r\n");
      out.write("        <div class=\"so-card\" style=\"padding-bottom:0\">\r\n");
      out.write("            <div class=\"so-stepper\" role=\"navigation\" aria-label=\"Tiến trình đăng ký\">\r\n");
      out.write("                <div class=\"so-stepper__item so-stepper__item--active\" tabindex=\"0\" role=\"tab\" aria-label=\"Bước 1: Thông tin Shop\">\r\n");
      out.write("                    <div class=\"so-stepper__dot\"><i class=\"fas fa-check so-stepper__dot-check\"></i></div>\r\n");
      out.write("                    <span class=\"so-stepper__label\">Thông tin Shop</span>\r\n");
      out.write("                    <div class=\"so-stepper__connector\"></div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"so-stepper__item\" tabindex=\"0\" role=\"tab\" aria-label=\"Bước 2: Cài đặt vận chuyển\">\r\n");
      out.write("                    <div class=\"so-stepper__dot\"><i class=\"fas fa-check so-stepper__dot-check\"></i></div>\r\n");
      out.write("                    <span class=\"so-stepper__label\">Cài đặt vận chuyển</span>\r\n");
      out.write("                    <div class=\"so-stepper__connector\"></div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"so-stepper__item\" tabindex=\"0\" role=\"tab\" aria-label=\"Bước 3: Thông tin thuế\">\r\n");
      out.write("                    <div class=\"so-stepper__dot\"><i class=\"fas fa-check so-stepper__dot-check\"></i></div>\r\n");
      out.write("                    <span class=\"so-stepper__label\">Thông tin thuế</span>\r\n");
      out.write("                    <div class=\"so-stepper__connector\"></div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"so-stepper__item\" tabindex=\"0\" role=\"tab\" aria-label=\"Bước 4: Thông tin định danh\">\r\n");
      out.write("                    <div class=\"so-stepper__dot\"><i class=\"fas fa-check so-stepper__dot-check\"></i></div>\r\n");
      out.write("                    <span class=\"so-stepper__label\">Thông tin định danh</span>\r\n");
      out.write("                    <div class=\"so-stepper__connector\"></div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"so-stepper__item\" tabindex=\"0\" role=\"tab\" aria-label=\"Bước 5: Hoàn tất\">\r\n");
      out.write("                    <div class=\"so-stepper__dot\"><i class=\"fas fa-check so-stepper__dot-check\"></i></div>\r\n");
      out.write("                    <span class=\"so-stepper__label\">Hoàn tất</span>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- ==================== STEP CONTENTS ==================== -->\r\n");
      out.write("        <div class=\"so-card\">\r\n");
      out.write("\r\n");
      out.write("            <!-- ========== STEP 1: THÔNG TIN SHOP ========== -->\r\n");
      out.write("            <div class=\"so-step-content\" id=\"step0\">\r\n");
      out.write("                <h2 class=\"so-step__title\">Thông tin Shop</h2>\r\n");
      out.write("                <p class=\"so-step__subtitle\">Vui lòng điền thông tin cơ bản của Shop bạn</p>\r\n");
      out.write("\r\n");
      out.write("                <!-- Tên Shop -->\r\n");
      out.write("                <div class=\"so-form-group\">\r\n");
      out.write("                    <label class=\"so-label so-label--required\" for=\"shopName\">Tên Shop</label>\r\n");
      out.write("                    <div class=\"so-input-wrap\">\r\n");
      out.write("                        <input type=\"text\" class=\"so-input\" id=\"shopName\" placeholder=\"Nhập tên Shop\" data-maxlength=\"30\" autocomplete=\"off\">\r\n");
      out.write("                        <span class=\"so-input-counter\">0/30</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"so-error-text\" id=\"shopNameError\"></div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <!-- Địa chỉ -->\r\n");
      out.write("                <div class=\"so-form-group\">\r\n");
      out.write("                    <label class=\"so-label so-label--required\">Địa chỉ lấy hàng</label>\r\n");
      out.write("                    <div id=\"addressDisplay\" style=\"padding:12px 16px;border:1px solid var(--so-border);border-radius:var(--so-radius-sm);min-height:48px;margin-bottom:8px;color:var(--so-text-hint);font-size:14px\">\r\n");
      out.write("                        Chưa có địa chỉ — bấm nút bên dưới để thêm\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <button type=\"button\" class=\"so-btn so-btn--secondary so-open-address-modal\" style=\"font-size:13px;padding:8px 20px\">\r\n");
      out.write("                        <i class=\"fas fa-plus\"></i> Thêm Địa Chỉ Mới\r\n");
      out.write("                    </button>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <!-- Email -->\r\n");
      out.write("                <div class=\"so-form-group\">\r\n");
      out.write("                    <label class=\"so-label\" for=\"shopEmail\">Email</label>\r\n");
      out.write("                    <div class=\"so-input-wrap\">\r\n");
      out.write("                        <input type=\"email\" class=\"so-input\" id=\"shopEmail\" placeholder=\"Nhập email liên hệ\" data-maxlength=\"100\">\r\n");
      out.write("                        <span class=\"so-input-counter\">0/100</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"so-error-text\"></div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <!-- Buttons -->\r\n");
      out.write("                <div class=\"so-btn-group\">\r\n");
      out.write("                    <div></div>\r\n");
      out.write("                    <div class=\"so-btn-group__right\">\r\n");
      out.write("                        <button type=\"button\" class=\"so-btn so-btn--secondary\" onclick=\"soSave()\">Lưu</button>\r\n");
      out.write("                        <button type=\"button\" class=\"so-btn so-btn--primary\" id=\"nextBtn0\" onclick=\"soNext()\">Tiếp theo</button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- ========== STEP 2: CÀI ĐẶT VẬN CHUYỂN ========== -->\r\n");
      out.write("            <div class=\"so-step-content\" id=\"step1\" hidden>\r\n");
      out.write("                <h2 class=\"so-step__title\">Phương thức vận chuyển</h2>\r\n");
      out.write("                <p class=\"so-step__subtitle\">Kích hoạt phương thức vận chuyển phù hợp</p>\r\n");
      out.write("\r\n");
      out.write("                <!-- Hỏa Tốc -->\r\n");
      out.write("                <div class=\"so-shipping-card\">\r\n");
      out.write("                    <div class=\"so-shipping-header\" onclick=\"toggleShippingBody('shippingBody1')\">\r\n");
      out.write("                        <h3>Hỏa Tốc</h3>\r\n");
      out.write("                        <button type=\"button\" class=\"so-shipping-collapse-btn\">Thu gọn <i class=\"fas fa-chevron-up\"></i></button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"so-shipping-body\" id=\"shippingBody1\">\r\n");
      out.write("                        <div class=\"so-shipping-row\">\r\n");
      out.write("                            <div class=\"so-shipping-row__left\">\r\n");
      out.write("                                <span class=\"so-shipping-name\">Hỏa Tốc</span>\r\n");
      out.write("                                <span class=\"so-cod-badge\">COD đã được kích hoạt</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"so-shipping-row__right\">\r\n");
      out.write("                                <label class=\"so-toggle\">\r\n");
      out.write("                                    <input type=\"checkbox\" id=\"toggleHoaToc\" checked>\r\n");
      out.write("                                    <span class=\"so-toggle__slider\"></span>\r\n");
      out.write("                                </label>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <!-- Nhanh -->\r\n");
      out.write("                <div class=\"so-shipping-card\">\r\n");
      out.write("                    <div class=\"so-shipping-header\" onclick=\"toggleShippingBody('shippingBody2')\">\r\n");
      out.write("                        <h3>Nhanh</h3>\r\n");
      out.write("                        <button type=\"button\" class=\"so-shipping-collapse-btn\">Thu gọn <i class=\"fas fa-chevron-up\"></i></button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"so-shipping-body\" id=\"shippingBody2\">\r\n");
      out.write("                        <div class=\"so-shipping-row\">\r\n");
      out.write("                            <div class=\"so-shipping-row__left\">\r\n");
      out.write("                                <span class=\"so-shipping-name\">Nhanh</span>\r\n");
      out.write("                                <span class=\"so-cod-badge\">COD đã được kích hoạt</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"so-shipping-row__right\">\r\n");
      out.write("                                <label class=\"so-toggle\">\r\n");
      out.write("                                    <input type=\"checkbox\" id=\"toggleNhanh\" checked>\r\n");
      out.write("                                    <span class=\"so-toggle__slider\"></span>\r\n");
      out.write("                                </label>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <!-- Tiết Kiệm -->\r\n");
      out.write("                <div class=\"so-shipping-card\">\r\n");
      out.write("                    <div class=\"so-shipping-header\" onclick=\"toggleShippingBody('shippingBody3')\">\r\n");
      out.write("                        <h3>Tiết Kiệm</h3>\r\n");
      out.write("                        <button type=\"button\" class=\"so-shipping-collapse-btn\">Thu gọn <i class=\"fas fa-chevron-up\"></i></button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"so-shipping-body\" id=\"shippingBody3\">\r\n");
      out.write("                        <div class=\"so-shipping-row\">\r\n");
      out.write("                            <div class=\"so-shipping-row__left\">\r\n");
      out.write("                                <span class=\"so-shipping-name\">Tiết kiệm</span>\r\n");
      out.write("                                <span class=\"so-cod-badge\">COD đã được kích hoạt</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"so-shipping-row__right\">\r\n");
      out.write("                                <label class=\"so-toggle\">\r\n");
      out.write("                                    <input type=\"checkbox\" id=\"toggleTietKiem\" checked>\r\n");
      out.write("                                    <span class=\"so-toggle__slider\"></span>\r\n");
      out.write("                                </label>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <!-- Thêm đơn vị vận chuyển -->\r\n");
      out.write("                <div class=\"so-shipping-card\" style=\"border-style:dashed;opacity:.7\">\r\n");
      out.write("                    <div class=\"so-shipping-header\">\r\n");
      out.write("                        <div>\r\n");
      out.write("                            <h3 style=\"font-size:14px\">Thêm Đơn Vị Vận Chuyển</h3>\r\n");
      out.write("                            <span style=\"font-size:12px;color:var(--so-text-hint)\">Các đơn vị vận chuyển khác được MarketplaceX hỗ trợ</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <button type=\"button\" class=\"so-shipping-collapse-btn\">Thu gọn <i class=\"fas fa-chevron-down\"></i></button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <!-- Buttons -->\r\n");
      out.write("                <div class=\"so-btn-group\">\r\n");
      out.write("                    <button type=\"button\" class=\"so-btn so-btn--secondary\" onclick=\"soPrev()\">Quay lại</button>\r\n");
      out.write("                    <div class=\"so-btn-group__right\">\r\n");
      out.write("                        <button type=\"button\" class=\"so-btn so-btn--secondary\" onclick=\"soSave()\">Lưu</button>\r\n");
      out.write("                        <button type=\"button\" class=\"so-btn so-btn--primary\" id=\"nextBtn1\" onclick=\"soNext()\">Tiếp theo</button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- ========== STEP 3: THÔNG TIN THUẾ ========== -->\r\n");
      out.write("            <div class=\"so-step-content\" id=\"step2\" hidden>\r\n");
      out.write("                <h2 class=\"so-step__title\">Thông tin thuế</h2>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"so-info-banner\">\r\n");
      out.write("                    <i class=\"fas fa-info-circle\"></i>\r\n");
      out.write("                    <span>Việc thu thập Thông Tin Thuế và Thông Tin Định Danh là bắt buộc theo quy định của Luật an ninh mạng, Thương mại điện tử và Thuế của Việt Nam. Thông Tin Thuế và Thông Tin Định Danh sẽ được bảo vệ theo chính sách bảo mật của MarketplaceX. Người bán hoàn toàn chịu trách nhiệm về tính chính xác của thông tin.</span>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <!-- Loại hình kinh doanh -->\r\n");
      out.write("                <div class=\"so-form-group\">\r\n");
      out.write("                    <label class=\"so-label so-label--required\">Loại hình kinh doanh</label>\r\n");
      out.write("                    <div class=\"so-radio-group\">\r\n");
      out.write("                        <label class=\"so-radio\"><input type=\"radio\" name=\"businessType\" value=\"caNhan\"> Cá nhân</label>\r\n");
      out.write("                        <label class=\"so-radio\"><input type=\"radio\" name=\"businessType\" value=\"hoKinhDoanh\" checked> Hộ kinh doanh</label>\r\n");
      out.write("                        <label class=\"so-radio\"><input type=\"radio\" name=\"businessType\" value=\"congTy\"> Công ty</label>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <!-- Tên công ty -->\r\n");
      out.write("                <div class=\"so-form-group\">\r\n");
      out.write("                    <label class=\"so-label so-label--required\" for=\"companyName\">Tên công ty</label>\r\n");
      out.write("                    <div class=\"so-input-wrap\">\r\n");
      out.write("                        <input type=\"text\" class=\"so-input\" id=\"companyName\" placeholder=\"Nhập vào\" data-maxlength=\"500\">\r\n");
      out.write("                        <span class=\"so-input-counter\">0/500</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <p class=\"so-label__hint\">Vui lòng điền đầy đủ tên công ty, không viết tắt. Ví dụ: \"Công ty Trách Nhiệm Hữu Hạn ABC\"</p>\r\n");
      out.write("                    <div class=\"so-error-text\"></div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <!-- Địa chỉ đăng ký kinh doanh -->\r\n");
      out.write("                <div class=\"so-form-group\">\r\n");
      out.write("                    <label class=\"so-label so-label--required\">Địa chỉ đăng ký kinh doanh</label>\r\n");
      out.write("                    <div class=\"so-form-row\">\r\n");
      out.write("                        <div class=\"so-form-group\">\r\n");
      out.write("                            <select class=\"so-select\" id=\"taxProvince\">\r\n");
      out.write("                                <option value=\"\">Chọn Tỉnh/Thành phố</option>\r\n");
      out.write("                            </select>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"so-form-group\">\r\n");
      out.write("                            <select class=\"so-select\" id=\"taxDistrict\">\r\n");
      out.write("                                <option value=\"\">Chọn Quận/Huyện</option>\r\n");
      out.write("                            </select>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"so-form-group\">\r\n");
      out.write("                            <select class=\"so-select\" id=\"taxWard\">\r\n");
      out.write("                                <option value=\"\">Chọn Phường/Xã</option>\r\n");
      out.write("                            </select>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <textarea class=\"so-textarea\" id=\"taxAddressDetail\" placeholder=\"Số nhà, tên đường, v.v..\" rows=\"3\"></textarea>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <!-- Email nhận hóa đơn -->\r\n");
      out.write("                <div class=\"so-form-group\">\r\n");
      out.write("                    <label class=\"so-label so-label--required\">Email nhận hóa đơn điện tử</label>\r\n");
      out.write("                    <div id=\"taxEmailList\" class=\"so-email-list\">\r\n");
      out.write("                        <div class=\"so-email-row\">\r\n");
      out.write("                            <div class=\"so-input-wrap\" style=\"flex:1\">\r\n");
      out.write("                                <input type=\"email\" class=\"so-input so-tax-email-input\" id=\"taxEmail0\" placeholder=\"Nhập email\" data-maxlength=\"100\">\r\n");
      out.write("                                <span class=\"so-input-counter\">0/100</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <button type=\"button\" class=\"so-add-email-btn\" onclick=\"addTaxEmail()\">\r\n");
      out.write("                        <i class=\"fas fa-plus\"></i> Thêm Email (tối đa 5)\r\n");
      out.write("                    </button>\r\n");
      out.write("                    <p class=\"so-label__hint\">Hóa đơn điện tử của bạn sẽ được gửi đến địa chỉ email này</p>\r\n");
      out.write("                    <div class=\"so-error-text\"></div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <!-- Mã số thuế -->\r\n");
      out.write("                <div class=\"so-form-group\">\r\n");
      out.write("                    <label class=\"so-label so-label--required\" for=\"taxId\">Mã số thuế</label>\r\n");
      out.write("                    <div class=\"so-input-wrap\">\r\n");
      out.write("                        <input type=\"text\" class=\"so-input\" id=\"taxId\" placeholder=\"Nhập vào\" data-maxlength=\"14\">\r\n");
      out.write("                        <span class=\"so-input-counter\">0/14</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <p class=\"so-label__hint\">Theo Quy định về Thương mại điện tử Việt Nam (Nghị định 52/2013/NĐ-CP), Người Bán phải cung cấp thông tin Mã số thuế cho sàn Thương mại điện tử.</p>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <!-- Giấy phép đăng ký kinh doanh -->\r\n");
      out.write("                <div class=\"so-form-group\">\r\n");
      out.write("                    <label class=\"so-label so-label--required\">Giấy phép đăng ký kinh doanh</label>\r\n");
      out.write("                    <div class=\"so-upload\">\r\n");
      out.write("                        <label class=\"so-upload__zone\" id=\"licenseUploadZone\">\r\n");
      out.write("                            <i class=\"fas fa-cloud-upload-alt\"></i>\r\n");
      out.write("                            <span>Upload</span>\r\n");
      out.write("                            <input type=\"file\" id=\"licenseUpload\" accept=\".jpg,.jpeg,.png\" onchange=\"handleFileUpload('licenseUpload','licensePreview','licenseFile')\">\r\n");
      out.write("                        </label>\r\n");
      out.write("                        <div id=\"licensePreview\"></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"so-error-text\"></div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <!-- Buttons -->\r\n");
      out.write("                <div class=\"so-btn-group\">\r\n");
      out.write("                    <button type=\"button\" class=\"so-btn so-btn--secondary\" onclick=\"soPrev()\">Quay lại</button>\r\n");
      out.write("                    <div class=\"so-btn-group__right\">\r\n");
      out.write("                        <button type=\"button\" class=\"so-btn so-btn--secondary\" onclick=\"soSave()\">Lưu</button>\r\n");
      out.write("                        <button type=\"button\" class=\"so-btn so-btn--primary\" id=\"nextBtn2\" onclick=\"soNext()\">Tiếp theo</button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- ========== STEP 4: THÔNG TIN ĐỊNH DANH ========== -->\r\n");
      out.write("            <div class=\"so-step-content\" id=\"step3\" hidden>\r\n");
      out.write("                <h2 class=\"so-step__title\">Thông tin định danh</h2>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"so-info-banner\">\r\n");
      out.write("                    <i class=\"fas fa-info-circle\"></i>\r\n");
      out.write("                    <span>Vui lòng cung cấp Thông Tin Định Danh của Chủ Shop (nếu là cá nhân), hoặc Người Đại Diện Pháp Lý trên giấy đăng ký kinh doanh.</span>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <!-- Hình thức định danh -->\r\n");
      out.write("                <div class=\"so-form-group\">\r\n");
      out.write("                    <label class=\"so-label so-label--required\">Hình Thức Định Danh</label>\r\n");
      out.write("                    <div class=\"so-radio-group\">\r\n");
      out.write("                        <label class=\"so-radio\"><input type=\"radio\" name=\"idType\" value=\"cccd\" checked onchange=\"updateIdTypeLabel()\"> Căn Cước Công Dân (CCCD)</label>\r\n");
      out.write("                        <label class=\"so-radio\"><input type=\"radio\" name=\"idType\" value=\"cmnd\" onchange=\"updateIdTypeLabel()\"> Chứng Minh Nhân Dân (CMND)</label>\r\n");
      out.write("                        <label class=\"so-radio\"><input type=\"radio\" name=\"idType\" value=\"passport\" onchange=\"updateIdTypeLabel()\"> Hộ chiếu</label>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <!-- Số CCCD -->\r\n");
      out.write("                <div class=\"so-form-group\">\r\n");
      out.write("                    <label class=\"so-label so-label--required\" for=\"idNumber\" id=\"idNumberLabel\">Số Căn Cước Công Dân (CCCD)</label>\r\n");
      out.write("                    <div class=\"so-input-wrap\">\r\n");
      out.write("                        <input type=\"text\" class=\"so-input\" id=\"idNumber\" placeholder=\"Nhập vào\" data-maxlength=\"12\">\r\n");
      out.write("                        <span class=\"so-input-counter\">0/12</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"so-error-text\"></div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <!-- Họ & Tên -->\r\n");
      out.write("                <div class=\"so-form-group\">\r\n");
      out.write("                    <label class=\"so-label so-label--required\" for=\"idFullName\">Họ & Tên</label>\r\n");
      out.write("                    <div class=\"so-input-wrap\">\r\n");
      out.write("                        <input type=\"text\" class=\"so-input\" id=\"idFullName\" placeholder=\"Nhập vào\" data-maxlength=\"100\">\r\n");
      out.write("                        <span class=\"so-input-counter\">0/100</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <p class=\"so-label__hint\">Theo CMND/CCCD/Hộ Chiếu</p>\r\n");
      out.write("                    <div class=\"so-error-text\"></div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <!-- Upload ảnh mặt trước -->\r\n");
      out.write("                <div class=\"so-form-group\">\r\n");
      out.write("                    <label class=\"so-label so-label--required\">Hình chụp của thẻ CMND/CCCD/Hộ chiếu</label>\r\n");
      out.write("                    <div class=\"so-upload\">\r\n");
      out.write("                        <label class=\"so-upload__zone\" id=\"idFrontUpload\">\r\n");
      out.write("                            <i class=\"fas fa-plus\"></i>\r\n");
      out.write("                            <span>Tải lên</span>\r\n");
      out.write("                            <input type=\"file\" id=\"idFrontInput\" accept=\".jpg,.jpeg,.png\" onchange=\"handleFileUpload('idFrontInput','idFrontPreview','idFrontFile')\">\r\n");
      out.write("                        </label>\r\n");
      out.write("                        <div id=\"idFrontPreview\"></div>\r\n");
      out.write("                        <div class=\"so-upload__sample\">\r\n");
      out.write("                            <div style=\"width:100%;height:100%;display:flex;align-items:center;justify-content:center;background:var(--so-bg);flex-direction:column;gap:4px\">\r\n");
      out.write("                                <i class=\"fas fa-id-card\" style=\"font-size:32px;color:var(--so-text-hint)\"></i>\r\n");
      out.write("                                <span style=\"font-size:10px;color:var(--so-text-hint)\">Ảnh mẫu</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <p class=\"so-upload-hint\">Vui lòng cung cấp ảnh chụp của CMND/CCCD/Hộ chiếu của bạn.<br>Các thông tin trong CMND/CCCD/Hộ chiếu phải được hiển thị rõ ràng (kích thước ảnh không vượt quá 5.0 MB)</p>\r\n");
      out.write("                    <div class=\"so-error-text\"></div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <!-- Upload ảnh cầm -->\r\n");
      out.write("                <div class=\"so-form-group\">\r\n");
      out.write("                    <label class=\"so-label so-label--required\">Ảnh đang cầm CMND/CCCD/Hộ chiếu của bạn</label>\r\n");
      out.write("                    <div class=\"so-upload\">\r\n");
      out.write("                        <label class=\"so-upload__zone\" id=\"idHoldUpload\">\r\n");
      out.write("                            <i class=\"fas fa-plus\"></i>\r\n");
      out.write("                            <span>Tải lên</span>\r\n");
      out.write("                            <input type=\"file\" id=\"idHoldInput\" accept=\".jpg,.jpeg,.png\" onchange=\"handleFileUpload('idHoldInput','idHoldPreview','idHoldFile')\">\r\n");
      out.write("                        </label>\r\n");
      out.write("                        <div id=\"idHoldPreview\"></div>\r\n");
      out.write("                        <div class=\"so-upload__sample\">\r\n");
      out.write("                            <div style=\"width:100%;height:100%;display:flex;align-items:center;justify-content:center;background:var(--so-bg);flex-direction:column;gap:4px\">\r\n");
      out.write("                                <i class=\"fas fa-user\" style=\"font-size:32px;color:var(--so-text-hint)\"></i>\r\n");
      out.write("                                <span style=\"font-size:10px;color:var(--so-text-hint)\">Ảnh mẫu</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <p class=\"so-upload-hint\">Vui lòng cung cấp ảnh bạn đang cầm CMND/CCCD/Hộ chiếu như ảnh mẫu.<br>Các thông tin trong CMND/CCCD/Hộ chiếu và hình ảnh của bạn phải được hiển thị rõ ràng (kích thước ảnh không vượt quá 5.0 MB)</p>\r\n");
      out.write("                    <div class=\"so-error-text\"></div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <!-- Checkbox xác nhận -->\r\n");
      out.write("                <div class=\"so-form-group\">\r\n");
      out.write("                    <label class=\"so-checkbox\">\r\n");
      out.write("                        <input type=\"checkbox\" id=\"agreePolicy\">\r\n");
      out.write("                        <span>Tôi xác nhận tất cả dữ liệu đã cung cấp là chính xác và trung thực. Tôi đã đọc và đồng ý với <a href=\"#\" style=\"color:var(--so-blue)\">Chính Sách Bảo Mật</a> của MarketplaceX.</span>\r\n");
      out.write("                    </label>\r\n");
      out.write("                    <div class=\"so-error-text\"></div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <!-- Buttons -->\r\n");
      out.write("                <div class=\"so-btn-group\">\r\n");
      out.write("                    <button type=\"button\" class=\"so-btn so-btn--secondary\" onclick=\"soPrev()\">Quay lại</button>\r\n");
      out.write("                    <div class=\"so-btn-group__right\">\r\n");
      out.write("                        <button type=\"button\" class=\"so-btn so-btn--secondary\" onclick=\"soSave()\">Lưu</button>\r\n");
      out.write("                        <button type=\"button\" class=\"so-btn so-btn--primary\" id=\"completeBtn\" onclick=\"soComplete()\">Hoàn tất</button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- ========== STEP 5: HOÀN TẤT ========== -->\r\n");
      out.write("            <div class=\"so-step-content\" id=\"step4\" hidden>\r\n");
      out.write("                <div class=\"so-success\">\r\n");
      out.write("                    <div class=\"so-success__icon\">\r\n");
      out.write("                        <i class=\"fas fa-check\"></i>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <h2 class=\"so-success__title\">Đăng ký thành công</h2>\r\n");
      out.write("                    <p class=\"so-success__text\">\r\n");
      out.write("                        Hãy đăng bán sản phẩm đầu tiên để khởi động hành trình bán hàng cùng MarketplaceX nhé!\r\n");
      out.write("                    </p>\r\n");
      out.write("                    <a href=\"home\" class=\"so-btn so-btn--primary\" style=\"padding:12px 40px;font-size:15px\">\r\n");
      out.write("                        <i class=\"fas fa-plus-circle\"></i> Thêm sản phẩm\r\n");
      out.write("                    </a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("        </div><!-- /.so-card -->\r\n");
      out.write("    </main>\r\n");
      out.write("\r\n");
      out.write("    <!-- ==================== ADDRESS MODAL ==================== -->\r\n");
      out.write("    <div class=\"so-modal-overlay\" id=\"addressModalOverlay\" role=\"dialog\" aria-modal=\"true\" aria-label=\"Thêm Địa Chỉ Mới\">\r\n");
      out.write("        <div class=\"so-modal\">\r\n");
      out.write("            <div class=\"so-modal__header\">\r\n");
      out.write("                <h3 class=\"so-modal__title\">Thêm Địa Chỉ Mới</h3>\r\n");
      out.write("                <button type=\"button\" class=\"so-modal__close\" id=\"addressModalClose\" aria-label=\"Đóng\">\r\n");
      out.write("                    <i class=\"fas fa-times\"></i>\r\n");
      out.write("                </button>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- Họ & Tên -->\r\n");
      out.write("            <div class=\"so-form-group\">\r\n");
      out.write("                <label class=\"so-label\" for=\"addrName\">Họ & Tên</label>\r\n");
      out.write("                <input type=\"text\" class=\"so-input\" id=\"addrName\" placeholder=\"Nhập vào\">\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- Số điện thoại -->\r\n");
      out.write("            <div class=\"so-form-group\">\r\n");
      out.write("                <label class=\"so-label\" for=\"addrPhone\">Số điện thoại</label>\r\n");
      out.write("                <input type=\"tel\" class=\"so-input\" id=\"addrPhone\" placeholder=\"Nhập vào\">\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- Địa chỉ -->\r\n");
      out.write("            <div class=\"so-form-group\">\r\n");
      out.write("                <label class=\"so-label\" style=\"font-weight:600;font-size:15px\">Địa chỉ</label>\r\n");
      out.write("                <label class=\"so-label\" style=\"font-size:13px;margin-top:8px\">Tỉnh/Thành phố/Quận/Huyện/Phường/Xã</label>\r\n");
      out.write("                <select class=\"so-select\" id=\"addrProvince\" style=\"margin-bottom:8px\">\r\n");
      out.write("                    <option value=\"\">Chọn</option>\r\n");
      out.write("                </select>\r\n");
      out.write("                <select class=\"so-select\" id=\"addrDistrict\" style=\"margin-bottom:8px\">\r\n");
      out.write("                    <option value=\"\">Chọn Quận/Huyện</option>\r\n");
      out.write("                </select>\r\n");
      out.write("                <select class=\"so-select\" id=\"addrWard\" style=\"margin-bottom:8px\">\r\n");
      out.write("                    <option value=\"\">Chọn Phường/Xã</option>\r\n");
      out.write("                </select>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- Địa chỉ chi tiết -->\r\n");
      out.write("            <div class=\"so-form-group\">\r\n");
      out.write("                <label class=\"so-label\" for=\"addrDetail\">Địa chỉ chi tiết</label>\r\n");
      out.write("                <textarea class=\"so-textarea\" id=\"addrDetail\" placeholder=\"Số nhà, tên đường, v.v..\" rows=\"3\"></textarea>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- Định vị -->\r\n");
      out.write("            <div class=\"so-form-group\">\r\n");
      out.write("                <button type=\"button\" class=\"so-geo-btn\" id=\"geoBtn\">\r\n");
      out.write("                    <i class=\"fas fa-map-marker-alt\"></i>\r\n");
      out.write("                    <div>\r\n");
      out.write("                        <div>Định vị</div>\r\n");
      out.write("                        <div class=\"so-geo-btn__sub\">Giúp đơn hàng được giao nhanh nhất</div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </button>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"so-modal__footer\">\r\n");
      out.write("                <button type=\"button\" class=\"so-btn so-btn--secondary\" id=\"addressModalCancel\">Hủy</button>\r\n");
      out.write("                <button type=\"button\" class=\"so-btn so-btn--primary\" id=\"addressModalSave\">Lưu</button>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- ==================== LIGHTBOX ==================== -->\r\n");
      out.write("    <div class=\"so-lightbox\" id=\"lightbox\" role=\"dialog\" aria-label=\"Xem ảnh phóng to\">\r\n");
      out.write("        <img src=\"\" alt=\"Preview phóng to\">\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("</div><!-- /.so-page -->\r\n");
      out.write("\r\n");
      out.write("<!-- Populate province dropdowns -->\r\n");
      out.write("<script>\r\n");
      out.write("document.addEventListener('DOMContentLoaded', function() {\r\n");
      out.write("    var provinces = [\r\n");
      out.write("        {id:'hcm',name:'TP. Hồ Chí Minh'},\r\n");
      out.write("        {id:'hn',name:'Hà Nội'},\r\n");
      out.write("        {id:'dn',name:'Đà Nẵng'},\r\n");
      out.write("        {id:'ag',name:'An Giang'},\r\n");
      out.write("        {id:'bdg',name:'Bình Dương'}\r\n");
      out.write("    ];\r\n");
      out.write("    ['addrProvince','taxProvince'].forEach(function(selId) {\r\n");
      out.write("        var sel = document.getElementById(selId);\r\n");
      out.write("        if (!sel) return;\r\n");
      out.write("        provinces.forEach(function(p) {\r\n");
      out.write("            var opt = document.createElement('option');\r\n");
      out.write("            opt.value = p.id;\r\n");
      out.write("            opt.textContent = p.name;\r\n");
      out.write("            sel.appendChild(opt);\r\n");
      out.write("        });\r\n");
      out.write("    });\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("<script src=\"js/seller_onboarding.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
