/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.19
 * Generated at: 2026-03-07 12:23:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import model.User;
import model.Address;
import java.util.List;

public final class user_005faddress_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(3);
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("model.User");
    _jspx_imports_classes.add("model.Address");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"vi\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Địa Chỉ | Shopee Việt Nam</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.1/normalize.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/style.css?v=2.0\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/user_profile.css?v=2.0\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/user_account.css?v=2.0\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div class=\"app\">\r\n");
      out.write("        <!-- HEADER -->\r\n");
      out.write("        <header class=\"header\">\r\n");
      out.write("            <nav class=\"header__navbar\">\r\n");
      out.write("                <ul class=\"header__navbar-list\">\r\n");
      out.write("                    <li class=\"header__navbar-item header__navbar-item--separate\"><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/seller-onboarding\" class=\"header__navbar-item-link\">Kênh Người Bán</a></li>\r\n");
      out.write("                    <li class=\"header__navbar-item header__navbar-item--separate\"><a href=\"#\" class=\"header__navbar-item-link\">Tải ứng dụng</a></li>\r\n");
      out.write("                    <li class=\"header__navbar-item\">Kết nối <a href=\"#\" class=\"header__navbar-item-link\"><i class=\"fab fa-facebook\"></i></a> <a href=\"#\" class=\"header__navbar-item-link\"><i class=\"fab fa-instagram\"></i></a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("                <ul class=\"header__navbar-list\">\r\n");
      out.write("                    <li class=\"header__navbar-item\"><a href=\"#\" class=\"header__navbar-item-link\"><i class=\"far fa-bell\"></i> Thông báo</a></li>\r\n");
      out.write("                    <li class=\"header__navbar-item\"><a href=\"#\" class=\"header__navbar-item-link\"><i class=\"far fa-question-circle\"></i> Hỗ Trợ</a></li>\r\n");
      out.write("                    ");
 User acc=(User) session.getAttribute("account"); if (acc !=null) { 
      out.write("\r\n");
      out.write("                        <li class=\"header__navbar-item header__navbar-item--separate\" style=\"font-weight: 500;\">\r\n");
      out.write("                            <div class=\"user-dropdown-wrapper\">\r\n");
      out.write("                                <div class=\"user-dropdown-trigger\" id=\"userDropdownTrigger\">\r\n");
      out.write("                                    <span class=\"user-avatar-small\">");
 if (acc.getAvatar() != null && !acc.getAvatar().trim().isEmpty()) { 
      out.write("<img src=\"");
      out.print( acc.getAvatar() );
      out.write("\" alt=\"Avatar\" onerror=\"this.onerror=null; this.src='https://cf.shopee.vn/file/40acfe9cc5ba0856aa76d0aece330f89_tn';\" style=\"width:22px;height:22px;border-radius:50%;object-fit:cover;vertical-align:middle;\">");
 } else { 
      out.write("<i class=\"fas fa-user-circle\"></i>");
 } 
      out.write("</span>\r\n");
      out.write("                                    <span>");
      out.print( acc.getFullName() );
      out.write("</span>\r\n");
      out.write("                                    <i class=\"fas fa-chevron-down user-dropdown-arrow\"></i>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"user-dropdown-menu\" id=\"userDropdownMenu\">\r\n");
      out.write("                                    <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/user/account/profile\" class=\"user-dropdown-item\">Tài Khoản Của Tôi</a>\r\n");
      out.write("                                    <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/user/purchase\" class=\"user-dropdown-item\">Đơn Mua</a>\r\n");
      out.write("                                    <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/logout\" class=\"user-dropdown-item\">Đăng Xuất</a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </li>\r\n");
      out.write("                    ");
 } 
      out.write("\r\n");
      out.write("                </ul>\r\n");
      out.write("            </nav>\r\n");
      out.write("            <div class=\"header-with-search\">\r\n");
      out.write("                <div class=\"header__logo\"><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/home\" class=\"header__logo-img-wrapper\"><i class=\"fa-solid fa-bag-shopping\"></i> Shopee</a></div>\r\n");
      out.write("                <div style=\"flex: 1;\"><div class=\"header__search\"><form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/search\" method=\"get\" class=\"header__search-input-wrap\" style=\"width:100%; display:flex;\"><input type=\"text\" name=\"txt\" class=\"header__search-input\" placeholder=\"Tìm kiếm sản phẩm\" style=\"flex:1;\"><button type=\"submit\" class=\"header__search-btn\"><i class=\"fas fa-search header__search-btn-icon\"></i></button></form></div></div>\r\n");
      out.write("                <div class=\"header__cart\"><div class=\"header__cart-wrap\"><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/cart\" style=\"text-decoration:none; color:inherit;\"><i class=\"fas fa-shopping-cart header__cart-icon\"></i><span class=\"header__cart-notice\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.cart != null ? sessionScope.cart.totalQuantity : 0}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span></a></div></div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </header>\r\n");
      out.write("\r\n");
      out.write("        <!-- TOAST -->\r\n");
      out.write("        ");
 String successMsg = (String) session.getAttribute("success"); String errorMsg = (String) session.getAttribute("error");
           if (successMsg != null) session.removeAttribute("success"); if (errorMsg != null) session.removeAttribute("error"); 
      out.write("\r\n");
      out.write("        ");
 if (successMsg != null) { 
      out.write("<div class=\"profile-toast success show\" id=\"profileToast\"><i class=\"fas fa-check-circle\"></i><span>");
      out.print( successMsg );
      out.write("</span></div>");
 } 
      out.write("\r\n");
      out.write("        ");
 if (errorMsg != null) { 
      out.write("<div class=\"profile-toast error show\" id=\"profileToast\"><i class=\"fas fa-exclamation-circle\"></i><span>");
      out.print( errorMsg );
      out.write("</span></div>");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <div class=\"app__container\">\r\n");
      out.write("            <div class=\"profile-container\">\r\n");
      out.write("                <!-- SIDEBAR -->\r\n");
      out.write("                <div class=\"profile-sidebar\">\r\n");
      out.write("                    <div class=\"profile-sidebar-mobile-toggle\" id=\"sidebarToggle\"><span class=\"toggle-text\"><i class=\"fas fa-bars\"></i> Menu tài khoản</span><i class=\"fas fa-chevron-down\"></i></div>\r\n");
      out.write("                    <div class=\"profile-sidebar-menu\" id=\"sidebarMenu\">\r\n");
      out.write("                        <div class=\"profile-sidebar-user\">\r\n");
      out.write("                            <div class=\"profile-sidebar-avatar\">");
 if (acc != null && acc.getAvatar() != null && !acc.getAvatar().trim().isEmpty()) { 
      out.write("<img src=\"");
      out.print( acc.getAvatar() );
      out.write("\" alt=\"Avatar\" onerror=\"this.onerror=null; this.src='https://cf.shopee.vn/file/40acfe9cc5ba0856aa76d0aece330f89_tn';\" style=\"width:100%;height:100%;border-radius:50%;object-fit:cover;\">");
 } else { 
      out.write("<i class=\"fas fa-user\"></i>");
 } 
      out.write("</div>\r\n");
      out.write("                            <div><div class=\"profile-sidebar-name\">");
      out.print( acc != null ? acc.getFullName() : "" );
      out.write("</div><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/user/account/profile\" class=\"profile-sidebar-edit\"><i class=\"fas fa-edit\"></i> Sửa Hồ Sơ</a></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"profile-menu-section\">\r\n");
      out.write("                            <div class=\"profile-menu-heading blue\"><i class=\"fas fa-user\"></i> Tài Khoản Của Tôi</div>\r\n");
      out.write("                            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/user/account/profile\" class=\"profile-menu-item\"><i class=\"fas fa-id-card\"></i> Hồ Sơ</a>\r\n");
      out.write("                            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/user/account/bank\" class=\"profile-menu-item\"><i class=\"fas fa-university\"></i> Ngân Hàng</a>\r\n");
      out.write("                            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/user/account/address\" class=\"profile-menu-item active\"><i class=\"fas fa-map-marker-alt\"></i> Địa Chỉ</a>\r\n");
      out.write("                            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/user/account/password\" class=\"profile-menu-item\"><i class=\"fas fa-lock\"></i> Đổi Mật Khẩu</a>\r\n");
      out.write("                            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/user/account/notification\" class=\"profile-menu-item\"><i class=\"fas fa-bell\"></i> Cài Đặt Thông Báo</a>\r\n");
      out.write("                            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/user/account/privacy\" class=\"profile-menu-item\"><i class=\"fas fa-shield-alt\"></i> Những Thiết Lập Riêng Tư</a>\r\n");
      out.write("                            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/user/account/personal\" class=\"profile-menu-item\"><i class=\"fas fa-user-tag\"></i> Thông Tin Cá Nhân</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"profile-menu-section\"><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/user/purchase\" class=\"profile-menu-heading red\" style=\"text-decoration:none;\"><i class=\"fas fa-clipboard-list\"></i> Đơn Mua</a></div>\r\n");
      out.write("                        <div class=\"profile-menu-section\"><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/user/voucher\" class=\"profile-menu-heading orange\" style=\"text-decoration:none;\"><i class=\"fas fa-ticket-alt\"></i> Kho Voucher</a></div>\r\n");
      out.write("                        <div class=\"profile-menu-section\"><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/user/coins\" class=\"profile-menu-heading green\" style=\"text-decoration:none;\"><i class=\"fas fa-coins\"></i> Shopee Xu</a></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <!-- MAIN CONTENT -->\r\n");
      out.write("                <div class=\"profile-main\">\r\n");
      out.write("                    <div class=\"account-card\">\r\n");
      out.write("                        <div class=\"address-header\">\r\n");
      out.write("                            <div class=\"account-card-title\">Địa Chỉ Của Tôi</div>\r\n");
      out.write("                            <button class=\"address-add-btn\" onclick=\"openAddModal()\"><i class=\"fas fa-plus\"></i> Thêm Địa Chỉ Mới</button>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        ");

                            List<Address> addresses = (List<Address>) request.getAttribute("addresses");
                            if (addresses != null && !addresses.isEmpty()) {
                                for (Address addr : addresses) {
                        
      out.write("\r\n");
      out.write("                            <div class=\"address-item\">\r\n");
      out.write("                                <div class=\"address-info\">\r\n");
      out.write("                                    <div class=\"address-name-phone\">\r\n");
      out.write("                                        ");
      out.print( addr.getFullName() );
      out.write(" <span>");
      out.print( addr.getPhone() );
      out.write("</span>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"address-detail\">");
      out.print( addr.getAddressDetail() );
      out.write("</div>\r\n");
      out.write("                                    ");
 if (addr.isDefault()) { 
      out.write("\r\n");
      out.write("                                        <div class=\"address-default-badge\">Mặc định</div>\r\n");
      out.write("                                    ");
 } 
      out.write("\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"address-actions\">\r\n");
      out.write("                                    <div>\r\n");
      out.write("                                        <button class=\"address-action-link\" onclick=\"openEditModal(");
      out.print( addr.getId() );
      out.write(',');
      out.write(' ');
      out.write('\'');
      out.print( addr.getFullName().replace("'", "\\'") );
      out.write("', '");
      out.print( addr.getPhone() );
      out.write("', '");
      out.print( addr.getAddressDetail().replace("'", "\\'") );
      out.write('\'');
      out.write(',');
      out.write(' ');
      out.print( addr.isDefault() );
      out.write(")\">Sửa</button>\r\n");
      out.write("                                        ");
 if (!addr.isDefault()) { 
      out.write("\r\n");
      out.write("                                        <form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/user/account/address\" method=\"post\" style=\"display:inline;\">\r\n");
      out.write("                                            <input type=\"hidden\" name=\"action\" value=\"delete\">\r\n");
      out.write("                                            <input type=\"hidden\" name=\"id\" value=\"");
      out.print( addr.getId() );
      out.write("\">\r\n");
      out.write("                                            <button type=\"submit\" class=\"address-action-link delete\" onclick=\"return confirm('Bạn có chắc muốn xóa địa chỉ này?')\">Xóa</button>\r\n");
      out.write("                                        </form>\r\n");
      out.write("                                        ");
 } 
      out.write("\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    ");
 if (!addr.isDefault()) { 
      out.write("\r\n");
      out.write("                                    <form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/user/account/address\" method=\"post\">\r\n");
      out.write("                                        <input type=\"hidden\" name=\"action\" value=\"setDefault\">\r\n");
      out.write("                                        <input type=\"hidden\" name=\"id\" value=\"");
      out.print( addr.getId() );
      out.write("\">\r\n");
      out.write("                                        <button type=\"submit\" class=\"address-set-default-btn\">Thiết lập mặc định</button>\r\n");
      out.write("                                    </form>\r\n");
      out.write("                                    ");
 } 
      out.write("\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        ");
  }
                            } else { 
      out.write("\r\n");
      out.write("                            <div class=\"account-empty\">\r\n");
      out.write("                                <div class=\"account-empty-icon\"><i class=\"fas fa-map-marker-alt\"></i></div>\r\n");
      out.write("                                <div class=\"account-empty-text\">Bạn chưa có địa chỉ nào</div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        ");
 } 
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- ADD/EDIT MODAL -->\r\n");
      out.write("    <div class=\"account-modal-overlay\" id=\"addressModal\">\r\n");
      out.write("        <div class=\"account-modal\">\r\n");
      out.write("            <button class=\"account-modal-close\" onclick=\"closeModal()\"><i class=\"fas fa-times\"></i></button>\r\n");
      out.write("            <div class=\"account-modal-title\" id=\"modalTitle\">Thêm Địa Chỉ Mới</div>\r\n");
      out.write("            <form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/user/account/address\" method=\"post\" id=\"addressForm\">\r\n");
      out.write("                <input type=\"hidden\" name=\"action\" id=\"modalAction\" value=\"add\">\r\n");
      out.write("                <input type=\"hidden\" name=\"id\" id=\"modalId\" value=\"\">\r\n");
      out.write("                <div class=\"account-form-row\">\r\n");
      out.write("                    <div class=\"account-form-label\">Họ và tên</div>\r\n");
      out.write("                    <div class=\"account-form-value\"><input type=\"text\" name=\"fullName\" id=\"modalFullName\" placeholder=\"Nhập họ và tên\" required></div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"account-form-row\">\r\n");
      out.write("                    <div class=\"account-form-label\">Số điện thoại</div>\r\n");
      out.write("                    <div class=\"account-form-value\"><input type=\"tel\" name=\"phone\" id=\"modalPhone\" placeholder=\"Nhập số điện thoại\" required></div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"account-form-row\">\r\n");
      out.write("                    <div class=\"account-form-label\">Địa chỉ cụ thể</div>\r\n");
      out.write("                    <div class=\"account-form-value\"><input type=\"text\" name=\"addressDetail\" id=\"modalAddress\" placeholder=\"Số nhà, đường, phường, quận, thành phố\" required></div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"account-form-row\">\r\n");
      out.write("                    <div class=\"account-form-label\"></div>\r\n");
      out.write("                    <div class=\"account-form-value\">\r\n");
      out.write("                        <label style=\"display:flex; align-items:center; gap:6px; font-size:14px; cursor:pointer;\">\r\n");
      out.write("                            <input type=\"checkbox\" name=\"isDefault\" id=\"modalDefault\" style=\"accent-color:#ee4d2d;\"> Đặt làm địa chỉ mặc định\r\n");
      out.write("                        </label>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"account-modal-actions\">\r\n");
      out.write("                    <button type=\"button\" class=\"account-cancel-btn\" onclick=\"closeModal()\">Hủy</button>\r\n");
      out.write("                    <button type=\"submit\" class=\"account-save-btn\">Hoàn thành</button>\r\n");
      out.write("                </div>\r\n");
      out.write("            </form>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <script>\r\n");
      out.write("        function openAddModal() {\r\n");
      out.write("            document.getElementById('modalTitle').textContent = 'Thêm Địa Chỉ Mới';\r\n");
      out.write("            document.getElementById('modalAction').value = 'add';\r\n");
      out.write("            document.getElementById('modalId').value = '';\r\n");
      out.write("            document.getElementById('modalFullName').value = '';\r\n");
      out.write("            document.getElementById('modalPhone').value = '';\r\n");
      out.write("            document.getElementById('modalAddress').value = '';\r\n");
      out.write("            document.getElementById('modalDefault').checked = false;\r\n");
      out.write("            document.getElementById('addressModal').classList.add('show');\r\n");
      out.write("        }\r\n");
      out.write("        function openEditModal(id, name, phone, address, isDefault) {\r\n");
      out.write("            document.getElementById('modalTitle').textContent = 'Cập Nhật Địa Chỉ';\r\n");
      out.write("            document.getElementById('modalAction').value = 'update';\r\n");
      out.write("            document.getElementById('modalId').value = id;\r\n");
      out.write("            document.getElementById('modalFullName').value = name;\r\n");
      out.write("            document.getElementById('modalPhone').value = phone;\r\n");
      out.write("            document.getElementById('modalAddress').value = address;\r\n");
      out.write("            document.getElementById('modalDefault').checked = isDefault;\r\n");
      out.write("            document.getElementById('addressModal').classList.add('show');\r\n");
      out.write("        }\r\n");
      out.write("        function closeModal() {\r\n");
      out.write("            document.getElementById('addressModal').classList.remove('show');\r\n");
      out.write("        }\r\n");
      out.write("        // Close on overlay click\r\n");
      out.write("        document.getElementById('addressModal').addEventListener('click', function(e) {\r\n");
      out.write("            if (e.target === this) closeModal();\r\n");
      out.write("        });\r\n");
      out.write("        // Sidebar & Toast\r\n");
      out.write("        (function() {\r\n");
      out.write("            var toggle = document.getElementById('sidebarToggle'), menu = document.getElementById('sidebarMenu');\r\n");
      out.write("            if (!toggle || !menu) return;\r\n");
      out.write("            if (window.innerWidth > 992) menu.classList.add('show');\r\n");
      out.write("            toggle.addEventListener('click', function() { menu.classList.toggle('show'); });\r\n");
      out.write("            window.addEventListener('resize', function() { if (window.innerWidth > 992) menu.classList.add('show'); });\r\n");
      out.write("        })();\r\n");
      out.write("        (function() { var t = document.getElementById('profileToast'); if (t) setTimeout(function() { t.classList.remove('show'); }, 3000); })();\r\n");
      out.write("    </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
