# CAU HINH KET NOI SQL SERVER (TU DONG PHAT HIEN)
db.url=jdbc:sqlserver://localhost;instanceName=SQLEXPRESS;databaseName=shopeeweb_lab211;encrypt=true;trustServerCertificate=true;
db.user=sa
db.password=zxczxc123

# GOOGLE OAUTH 2.0
google.client.id=403118955858-9mf0sg0uimot3dk9e03jqjs7n3tjuvfe.apps.googleusercontent.com
google.client.secret=

# FACEBOOK OAUTH 2.0
facebook.app.id=
facebook.app.secret=
